WIZARD_URL, WIZARD_SUPPORT, WIZARD_CARD_NUM, WIZARD_CARD_NAME, WIZARD_CRYPTO_MID, WIZARD_CRYPTO_KEY, WIZARD_CURRENCY = range(7)

PLAN_CREATE_NAME, PLAN_CREATE_DATA, PLAN_CREATE_DAYS, PLAN_CREATE_IP, PLAN_CREATE_PRICE, PLAN_CREATE_NODES = range(10, 16)
PLAN_EDIT_VALUE = 16
PLAN_EDIT_NODES = 17
PLAN_BULK_NODES = 18
PLAN_BULK_CREATE_NODES = 19
PLAN_BULK_CREATE_MATRIX = 20
PLAN_BULK_DELETE = 23
PLAN_BULK_NODES_PLANS = 24

ADMIN_ADD_ID, ADMIN_ADD_PERMS = range(21, 23)
ADMIN_MANUAL_SUB_COMMENT, ADMIN_MANUAL_SUB_DATA, ADMIN_MANUAL_SUB_DAYS, ADMIN_MANUAL_SUB_IP, ADMIN_MANUAL_SUB_NODES, ADMIN_MANUAL_SUB_NOTE = range(30, 36)

SETTINGS_CARD_NUM, SETTINGS_CARD_NAME = range(40, 42)
SETTINGS_CRYPTO_MID, SETTINGS_CRYPTO_KEY = range(42, 44)
SETTINGS_SUPPORT = 44
SETTINGS_SYNC = 46
SETTINGS_GG_URL = 47
SETTINGS_UPDATE_HTTP_PROXY = 48
SETTINGS_UPDATE_HTTPS_PROXY = 49
SETTINGS_FORCE_JOIN_CHANNEL = 52
SETTINGS_GHOSTPAY_URL = 53
SETTINGS_GHOSTPAY_KEY = 54
SETTINGS_PLAN_PAGE_SIZE_CONSUMER = 55
SETTINGS_PLAN_PAGE_SIZE_ADMIN = 56
SETTINGS_GP_PAIR_RATE = 57
SETTINGS_USDT_TRC20_RATE = 58
SETTINGS_USDT_BSC_RATE = 59
SETTINGS_USDT_POL_RATE = 60

USER_SEARCH = 50
SUB_SEARCH = 51

CARD_WAIT_RECEIPT = 60
REQUEST_REASON = 61
ADMIN_REJECT_REASON = 62
ADMIN_BROADCAST = 63

CURR_ADD_CODE, CURR_ADD_NAME, CURR_ADD_DECIMALS, CURR_ADD_METHODS, CURR_ADD_RATE, CURR_EDIT_RATE = range(70, 76)

SETTINGS_TRIAL_DATA, SETTINGS_TRIAL_EXPIRE, SETTINGS_TRIAL_NODES = range(80, 83)
USDT_MANUAL_TX = 90
SETTINGS_USDT_TRC20, SETTINGS_USDT_BSC, SETTINGS_USDT_POLYGON = range(91, 94)
SETTINGS_TRIAL_NOTE = 95
SETTINGS_PAID_NOTE = 96
ADMIN_SUB_BULK_NOTE_SELECT = 97
ADMIN_SUB_BULK_NOTE_INPUT = 98
SETTINGS_TRIAL_DISABLED_MSG = 99
SETTINGS_TRIAL_MAX_CLAIMS = 100
SETTINGS_DISCOUNT_CODE_CODE = 101
SETTINGS_DISCOUNT_CODE_PCT = 110
SETTINGS_DISCOUNT_CODE_MAXUSES = 111
CONSUMER_DISCOUNT_INPUT = 112
PLAN_BULK_ENABLE_DISABLE = 103
PLAN_BULK_PRICE_MULTIPLY = 104
PLAN_BULK_PRICE_FACTOR = 113
OFFER_CREATE_NAME = 105
OFFER_CREATE_DISCOUNT = 106
OFFER_CREATE_PLANS = 107
SETTINGS_START_MSG = 108
ADMIN_LOG_VIEW = 109

REF_PKG_CREATE_NAME = 130
REF_PKG_CREATE_CREDITS = 131
REF_PKG_CREATE_DATA = 132
REF_PKG_CREATE_DAYS = 133
REF_PKG_CREATE_IP = 134
REF_PKG_CREATE_NODES = 135
REF_PKG_EDIT_NODES = 136
REF_PKG_BULK_NODES_PKGS = 137
REF_PKG_BULK_NODES = 138
SETTINGS_DISCOUNT_CODE_PLANS = 114
SETTINGS_DISCOUNT_CODE_MAX_AMOUNT = 115
ADMIN_BROADCAST_INPUT = 116
SETTINGS_NOTIF_SUB_MSG = 117
ADMIN_WALLET_ADD = 140
ADMIN_WALLET_REMOVE = 141
SETTINGS_REF_COMMISSION_PCT = 142
CONSUMER_WALLET_TOPUP_AMOUNT = 143
