WIZARD_URL, WIZARD_SUPPORT, WIZARD_CARD_NUM, WIZARD_CARD_NAME, WIZARD_CRYPTO_MID, WIZARD_CRYPTO_KEY, WIZARD_CURRENCY = range(7)

PLAN_CREATE_NAME, PLAN_CREATE_DATA, PLAN_CREATE_DAYS, PLAN_CREATE_IP, PLAN_CREATE_PRICE, PLAN_CREATE_NODES = range(10, 16)
PLAN_EDIT_VALUE = 16
PLAN_EDIT_NODES = 17
PLAN_BULK_NODES = 18
PLAN_BULK_CREATE_NODES = 19
PLAN_BULK_CREATE_MATRIX = 20
PLAN_BULK_DELETE = 23
PLAN_BULK_NODES_PLANS = 24

ADMIN_ADD_ID, ADMIN_ADD_PERMS = range(21, 23)
ADMIN_MANUAL_SUB_COMMENT, ADMIN_MANUAL_SUB_DATA, ADMIN_MANUAL_SUB_DAYS, ADMIN_MANUAL_SUB_IP, ADMIN_MANUAL_SUB_NODES, ADMIN_MANUAL_SUB_NOTE = range(30, 36)

SETTINGS_CARD_NUM, SETTINGS_CARD_NAME = range(40, 42)
SETTINGS_CRYPTO_MID, SETTINGS_CRYPTO_KEY = range(42, 44)
SETTINGS_SUPPORT = 44
SETTINGS_SYNC = 46
SETTINGS_GG_URL = 47
SETTINGS_UPDATE_HTTP_PROXY = 48
SETTINGS_UPDATE_HTTPS_PROXY = 49
SETTINGS_FORCE_JOIN_CHANNEL = 52
SETTINGS_GHOSTPAY_URL = 53
SETTINGS_GHOSTPAY_KEY = 54
SETTINGS_PLAN_PAGE_SIZE_CONSUMER = 55
SETTINGS_PLAN_PAGE_SIZE_ADMIN = 56
SETTINGS_GP_PAIR_RATE = 57
SETTINGS_USDT_TRC20_RATE = 58
SETTINGS_USDT_BSC_RATE = 59
SETTINGS_USDT_POL_RATE = 60

USER_SEARCH = 50
SUB_SEARCH = 51

CARD_WAIT_RECEIPT = 60
REQUEST_REASON = 61
ADMIN_REJECT_REASON = 62
ADMIN_BROADCAST = 63

CURR_ADD_CODE, CURR_ADD_NAME, CURR_ADD_DECIMALS, CURR_ADD_METHODS, CURR_ADD_RATE, CURR_EDIT_RATE = range(70, 76)

SETTINGS_TRIAL_DATA, SETTINGS_TRIAL_EXPIRE, SETTINGS_TRIAL_NODES = range(80, 83)
USDT_MANUAL_TX = 90
SETTINGS_USDT_TRC20, SETTINGS_USDT_BSC, SETTINGS_USDT_POLYGON = range(91, 94)
SETTINGS_TRIAL_NOTE = 95
SETTINGS_PAID_NOTE = 96
ADMIN_SUB_BULK_NOTE_SELECT = 97
ADMIN_SUB_BULK_NOTE_INPUT = 98
