from config import settings

_EN = {
    "welcome": "👋 Welcome!\n\nBrowse plans or check your subscription status below.",
    "banned": "You are banned from using this bot.",
    "no_plans": "No plans available at the moment. Please check back later.",
    "plans_header": "📦 *Available Plans:*",
    "no_active_subs": "You have no active subscriptions. Use /plans to purchase one.",
    "sub_removed": "❌ Subscription expired or removed.",
    "support_contact": "💬 For support, contact: {support}",
    "support_no_contact": "💬 Please contact the bot administrator for support.",
    "support_purchase": "\n\nPlease contact {support} to purchase.",
    "support_purchase_no_contact": "\n\nPlease contact support to purchase.",
    "plan_detail": "📦 *{name}*\n\n💾 Data: {data_text}\n📅 Duration: {days_text}\n📱 IP Limit: {ip_text}",
    "plan_price_line_card": "💳 Card: {price}",
    "plan_price_line_crypto": "🪙 Crypto: {price}",
    "plan_price_line_request": "🙋 Request: {price}",
    "plan_price_line_manual": "🧾 Manual Payment: {price}",
    "plan_price_fallback": "💰 Price: {price}",
    "card_payment_info": "💳 Transfer *{price}* to the card below.\nCard number:\n`{card_number}`\nName: *{card_holder}*\n\nAfter payment, send your receipt screenshot here.",
    "receipt_received": "Receipt received! ⏳ Waiting for admin confirmation.",
    "receipt_caption": "📩 New Payment Receipt\n\n👤 {first_name} ({username})\n🆔 {telegram_id}\n📦 Plan: {plan_name}\n💰 Amount: {amount}",
    "sub_confirmed": "✅ Your subscription has been confirmed!\n\n🔗 Link: `{url}`\n\nImport this link into your VPN app.",
    "sub_rejected": "❌ Your payment was rejected. Please contact support if you believe this is an error.",
    "request_created": "🙋 Your subscription request has been submitted. An admin will review it shortly.",
    "request_caption": "🙋 Subscription Request\n\n👤 {first_name} ({username})\n🆔 {telegram_id}\n📦 Plan: {plan_name}\n📝 Reason: {reason}",
    "request_no_reason": "(no reason provided)",
    "request_approved": "✅ Your subscription request has been approved!\n\n🔗 Link: `{url}`\n\nImport this link into your VPN app.",
    "request_declined": "❌ Your subscription request was declined.",
    "manual_request_created": "🧾 Manual payment request sent. Admin will review and approve/reject it.",
    "manual_request_caption": "🧾 Manual Payment Request\n\n👤 {first_name} ({username})\n🆔 {telegram_id}\n📦 Plan: {plan_name}\n💰 Amount: {amount}",
    "manual_chain_prompt": "🧾 *Manual USDT Payment*\n\nSelect your preferred network:",
    "manual_send_proof": "Network: *{chain}*\nAmount: *{amount}*\nAddress:\n`{address}`\n\nSend your tx hash after payment:",
    "manual_proof_received": "✅ Tx hash received. Admin will verify and approve/reject.",
    "manual_no_address": "Manual USDT payment is not configured yet.",
    "crypto_invoice_created": "🪙 Pay with Crypto\n\nAmount: {amount}\n\nClick the button below to complete payment.",
    "crypto_paid": "✅ Crypto payment confirmed!\n\n🔗 Link: `{url}`\n\nImport this link into your VPN app.",
    "service_unavailable": "⚠️ Service temporarily unavailable. Please try again later.",
    "sub_orphaned": "⚠️ Your subscription has been removed from the server. Please contact support.",
    "admin_confirmed": "✅ Confirmed by {admin}\nSub ID: {sub_id}",
    "admin_rejected": "❌ Rejected by {admin}",
    "wizard_step1": "⚙️ *First-Run Setup*\n\nStep 1/4 — GhostGate URL\n\nEnter the full panel URL including the secret path.\nExample: `https://vpn.example.com/mySecretPath`",
    "wizard_step1_fail": "❌ Could not connect: {error}\n\nTry again:",
    "wizard_step2": "Step 2/4 — Support Contact\n\nEnter a @username for users to contact for support. (e.g. @support)",
    "wizard_step3a": "Step 3/4 — Card-to-Card Payment\n\nEnter card number (e.g. 6037-9975-XXXX-XXXX):",
    "wizard_step3b": "Enter cardholder name:",
    "wizard_step3c": "Step 3/4 — Cryptomus (optional)\n\nEnter your Cryptomus Merchant ID:",
    "wizard_step3d": "Enter your Cryptomus API Key:",
    "wizard_step4": "Step 4/4 — Base Currency\n\nEnter base currency code (e.g. IRT, USD, USDT):\nThis is the unit in which plan prices will be set.",
    "wizard_done": "✅ Setup complete!\n\nYou can add more currencies with different exchange rates in Settings → Currencies.",
    "btn_skip": "⏭️ Skip",
    "btn_back": "⬅️ Back",
    "btn_done": "✅ Done",
    "btn_cancel": "❌ Cancel",
    "btn_buy_plan": "🛒 Buy {name}",
    "btn_select_all": "✅ Select All",
    "btn_unselect_all": "⬜ Unselect All",
    "btn_join_channel": "📢 Join Channel",
    "btn_i_have_joined": "✅ I've Joined",
    "btn_yes": "✅ Yes",
    "btn_no": "❌ No",
    "btn_delete": "🗑️ Delete",
    "btn_move_up": "⬆️ Move Up",
    "btn_move_down": "⬇️ Move Down",
    "btn_confirm": "✅ Confirm",
    "btn_reject": "❌ Reject",
    "btn_adm_subs": "📋 Subscriptions",
    "btn_adm_plans": "🗂️ Plans",
    "btn_adm_users": "👥 Users",
    "btn_adm_admins": "👑 Admins",
    "btn_adm_orders": "💰 Orders",
    "btn_adm_settings": "⚙️ Settings",
    "btn_adm_update": "🔄 Update Bot",
    "btn_set_gg": "🔗 GhostGate Connection",
    "btn_set_card": "💳 Card-to-Card",
    "btn_set_crypto": "🪙 Crypto Providers",
    "btn_set_requests": "🙋 Request Flow",
    "btn_set_support": "📝 Support Contact",
    "btn_set_currencies": "💱 Currencies",
    "btn_set_trial": "🎁 Trial Subscription",
    "btn_set_paid_note": "📝 Paid Sub Note",
    "btn_set_usdt": "🧾 USDT Addresses",
    "btn_set_sync": "🔄 Sync Interval",
    "btn_set_plans_pagination": "📄 Plans Pagination",
    "btn_set_force_join": "📢 Force Join Channel",
    "btn_set_plan_start_after_use": "⏱️ Plan Expiry On First Use",
    "btn_set_trial_start_after_use": "🎁 Trial Expiry On First Use",
    "btn_set_update_http_proxy": "🌐 Update HTTP Proxy",
    "btn_set_update_https_proxy": "🔐 Update HTTPS Proxy",
    "btn_curr_add": "➕ Add Currency",
    "btn_curr_set_base": "📌 Set Base",
    "btn_method_card": "💳 Card",
    "btn_method_crypto": "🪙 Crypto",
    "btn_method_request": "🙋 Request",
    "btn_method_manual": "🧾 Manual",
    "btn_sub_stats": "📊 Stats & QR",
    "btn_sub_configs": "🔗 Node Configs",
    "btn_ban": "🚫 Ban",
    "btn_unban": "🔓 Unban",
    "btn_reset_trial": "🔄 Reset Trial",
    "adm_trial_reset_user_done": "✅ Trial reset for this user.",
    "adm_trial_no_claim": "ℹ️ This user has no trial claim.",
    "btn_activate": "✅ Activate",
    "btn_deactivate": "❌ Deactivate",
    "btn_edit_price": "✏️ Edit Price",
    "btn_edit_name": "✏️ Edit Name",
    "btn_edit_nodes": "🖥️ Edit Nodes",
    "btn_edit_rate": "✏️ Edit Rate",
    "btn_edit_card_num": "✏️ Edit Card Number",
    "btn_edit_card_name": "✏️ Edit Holder Name",
    "btn_edit_mid": "✏️ Cryptomus Merchant ID",
    "btn_edit_api_key": "✏️ Cryptomus API Key",
    "btn_edit_gp_url": "✏️ GhostPayments URL",
    "btn_edit_gp_key": "✏️ GhostPayments API Key",
    "btn_consumer_plans": "📦 Plans",
    "btn_consumer_status": "📊 My Status",
    "btn_consumer_support": "💬 Support",
    "btn_consumer_trial": "🎁 Free Trial",
    "btn_trial_claim": "🎁 Claim Free Trial",
    "btn_regen_link": "🔄 Regenerate Link",
    "btn_sub_disable": "⛔ Disable",
    "btn_sub_enable": "✅ Enable",
    "sub_disabled": "⛔ Subscription disabled.",
    "sub_enabled": "✅ Subscription re-enabled.",
    "sub_toggle_fail": "❌ Failed to update subscription.",
    "crypto_paid_admin": "💰 *Crypto Payment Received*\n\n👤 {first_name} ({username})\n🆔 {telegram_id}\n📦 Plan: {plan_name}\n💰 Amount: {amount} {currency}",
    "btn_pay_card": "💳 Pay by Card Transfer",
    "btn_pay_crypto": "🪙 Pay with Crypto",
    "btn_request_sub": "🙋 Request Subscription",
    "btn_pay_manual": "🧾 USDT (TRC20/BSC/POL)",
    "btn_open_payment": "💳 Open payment page",
    "adm_enabled": "✅ Enabled",
    "adm_toggle_btn": "Toggle: {status}",
    "adm_requests_title": "🙋 *Request Flow*",
    "adm_user_orders_title": "📋 User orders:",
    "adm_orders_title": "💰 *Orders*\n\n⏳ Pending: {count}",
    "adm_orders_pending_waiting": "⏳ Pending/Waiting",
    "adm_orders_paid": "✅ Paid",
    "adm_orders_rejected": "❌ Rejected",
    "adm_admins_title": "👑 *Admins*\nRoot: `{root_id}`",
    "adm_add_admin_btn": "➕ Add Admin",
    "adm_remove_btn": "🗑️ Remove",
    "adm_create_plan_btn": "➕ Create Plan",
    "adm_bulk_create_btn": "📊 Bulk Create Matrix",
    "adm_bulk_nodes_btn": "🖥️ Bulk Edit Nodes",
    "adm_bulk_delete_btn": "🗑️ Bulk Delete Plans",
    "adm_bulk_delete_prompt": "Select plans to delete:",
    "adm_bulk_delete_done": "✅ Deleted {count} plans.",
    "adm_bulk_enable_btn": "✅ Bulk Enable Plans",
    "adm_bulk_disable_btn": "❌ Bulk Disable Plans",
    "adm_bulk_enable_prompt": "Select plans to enable:",
    "adm_bulk_disable_prompt": "Select plans to disable:",
    "adm_bulk_enable_done": "✅ Enabled {count} plans.",
    "adm_bulk_disable_done": "❌ Disabled {count} plans.",
    "adm_bulk_price_multiply_btn": "✖️ Bulk Multiply Prices",
    "adm_bulk_price_divide_btn": "➗ Bulk Divide Prices",
    "adm_bulk_price_select_plans": "Select plans to apply price change to:",
    "adm_bulk_price_factor_prompt": "Enter multiply/divide factor (e.g. 1.1 for +10%, 0.9 for -10%, 2 for double):",
    "adm_bulk_price_done": "✅ Prices updated for {count} plans.",
    "adm_bulk_nodes_select_plans_prompt": "Select plans for node update:",
    "adm_bulk_create_nodes_prompt": "Select nodes for all generated plans:",
    "adm_bulk_create_matrix_prompt": "Send monthly prices table (flexible):\n`10: p1,p2,p3,p4`\n`20 p1 p2 p3 p4`\n`1000|p1|p2|p3|p4`\n\nFirst value=data(GB or TB). Next columns=IP1..IPN.\nFor IRT, `k` is allowed (e.g. 80k). Days is fixed to 30.",
    "adm_bulk_create_bad_data": "Invalid/missing data rows.",
    "adm_bulk_create_bad_price": "Invalid prices or inconsistent IP column count.",
    "adm_bulk_create_done": "✅ Bulk plans saved.\nCreated: {created}\nUpdated: {updated}",
    "adm_plan_nodes_edit_prompt": "Select nodes for this plan:",
    "adm_plan_nodes_bulk_prompt": "Select nodes to apply to all plans:",
    "adm_plan_nodes_bulk_done": "✅ Nodes updated for {count} plans.",
    "irt_price_step": "For IRT, price must be at least 1000 and in 1000 steps.",
    "adm_search_btn": "🔍 Search",
    "adm_create_btn": "➕ Create",
    "adm_search_user_btn": "🔍 Search user",
    "adm_trial_set_data": "✏️ Set Data GB",
    "adm_trial_set_expire": "✏️ Set Expire Time",
    "adm_trial_set_nodes": "🖥️ Configure Nodes",
    "adm_trial_set_note": "📝 Set Note",
    "trial_note_prompt": "Enter a note for trial subscriptions (send - to remove):\nCurrent: {current}",
    "adm_trial_nodes_prompt": "🎁 Select nodes for trial subscription:",
    "adm_update_checking": "🔄 Checking for updates...",
    "adm_update_none": "✅ Already up to date.",
    "adm_update_starting": "⬇️ Updating to {version}...",
    "adm_update_failed": "❌ Update failed. Check logs.",
    "adm_force_join_title": "📢 *Force Join Channels*\n\nStatus: {status}\n\nChannels:\n{channels}",
    "adm_force_join_set_channel": "➕ Add Channel",
    "adm_force_join_prompt": "Send channel username or ID to add (e.g. `@mychannel` or `-100...`).",
    "adm_force_join_no_channels": "(none)",
    "adm_force_join_remove_btn": "🗑️ Remove {channel}",
    "adm_plan_after_use_status": "⏱️ Plan expiry from first use: {status}",
    "adm_trial_after_use_status": "🎁 Trial expiry from first use: {status}",
    "force_join_required": "To use the bot, please join {channel} first.",
    "force_join_alert": "Join the required channel first.",
    "adm_usdt_title": "🧾 *USDT Manual Payment*\n\nStatus: {status}\n\nTRC20: `{trc20}`\nBSC: `{bsc}`\nPOLYGON: `{polygon}`",
    "adm_usdt_rate_prompt": "1 USDT = ? {base} for {chain}\n\n(e.g. enter 168000 if 1 USDT = 168,000 IRT):",
    "adm_enter_usdt_trc20": "Enter USDT TRC20 address:",
    "adm_enter_usdt_bsc": "Enter USDT BSC address:",
    "adm_enter_usdt_polygon": "Enter USDT POLYGON address:",
    "admin_menu_title": "👑 *Admin Panel*\nVersion: `{version}`",
    "plans_title": "🗂️ *Plans*\n\nSelect a plan to manage:",
    "plans_page_info": "Page {page}/{pages}",
    "no_plans_admin": "No plans created yet.",
    "plan_created": "✅ Plan created.",
    "plan_deleted": "🗑️ Plan deleted.",
    "setting_saved": "✅ Setting saved.",
    "enter_value": "Enter new value:",
    "sub_created_admin": "✅ Subscription created.\nSub ID: {sub_id}\nLink: `{url}`",
    "sub_deleted": "🗑️ Subscription deleted.",
    "user_banned": "🚫 User banned.",
    "user_unbanned": "🔓 User unbanned.",
    "admin_added": "✅ Admin added.",
    "admin_removed": "🗑️ Admin removed.",
    "invalid_input": "❌ Invalid input. Please try again.",
    "order_not_found": "Order not found.",
    "ghostgate_error": "❌ Failed to communicate with GhostGate. Please try again.",
    "reason_prompt": "Do you want to provide a reason? Type it or press Skip:",
    "reject_reason_prompt": "Enter rejection reason (or press Skip to send without reason):",
    "reject_notif": "❌ Your payment was rejected.\n\nReason: {reason}",
    "curr_title": "💱 *Currencies*\nBase: {base}\n\nSelect a currency to manage:",
    "curr_no_currencies": "💱 *Currencies*\nBase: {base}\n\nNo additional currencies configured.",
    "curr_detail": "💱 *{code}* — {name}\nDecimals: {decimals}\nMethods: {methods}\nRate: 1 {base} = {rate} {code}",
    "curr_add_code": "Enter currency code (e.g. IRT, USDT, USD):",
    "curr_add_name": "Enter display name (e.g. Toman, Tether, Dollar):",
    "curr_add_decimals": "Enter decimal places (0 for IRT, 2 for USDT):",
    "curr_add_methods": "Select which payment methods use this currency:",
    "curr_add_rate_prompt": "1 {code} = ? {base}\n\n(e.g. enter 40000 if 1 USDT = 40,000 IRT):",
    "curr_added": "✅ Currency {code} added.",
    "curr_deleted": "🗑️ Currency deleted.",
    "curr_rate_updated": "✅ Rate updated.",
    "curr_set_base_prompt": "Select which currency to use as base (plan prices are entered in this unit):",
    "curr_base_set": "✅ Base currency set to {code}.",
    "plan_price_enter": "Enter price in {base} (e.g. 500000):",
    "trial_info": "🎁 *Free Trial*\n\n{data_gb} GB • {expire_h}h\n{start_text}{requirement_text}\n\nClaim your one-time free trial!",
    "trial_start_from_connection": "Validity starts from your first connection.",
    "trial_start_from_get": "Validity starts from now.",
    "trial_not_available": "🎁 Free trial is not available at the moment.",
    "trial_already_claimed": "🎁 You have already claimed your free trial.",
    "trial_claimed": "🎁 Your free trial is ready!\n\n🔗 Link: `{url}`\n\nImport this link into your VPN app. {start_text}",
    "trial_plan_name": "Free Trial",
    "trial_settings": "🎁 *Trial Subscription*\n\nStatus: {status}\nData: {data_gb} GB\nExpiry: {expire_h}h\nNodes: {node_count} configured{requirement_text}",
    "trial_data_prompt": "Enter trial data limit in GB (e.g. 0.5):",
    "trial_expire_prompt": "Enter trial duration in hours (e.g. 24, or 0.5 for 30 min):",
    "adm_trial_set_disabled_msg": "✏️ Set Disabled Message",
    "adm_trial_disabled_msg_prompt": "Enter message shown when trial is disabled (send - to use default):\nCurrent: {current}",
    "adm_trial_set_max_claims": "🔢 Set Claim Limit",
    "adm_trial_max_claims_prompt": "Enter max number of trial claims (0 = unlimited):\nCurrent: {current}",
    "adm_trial_set_referral_requirement": "👥 Set Referral Requirement",
    "adm_trial_referral_requirement_prompt": "Enter required referral credits for trial access (0 = disabled):\nCurrent: {current}",
    "adm_trial_referral_requirement_status": "👥 Referral requirement: {required}",
    "adm_trial_reset_claims_btn": "🔄 Reset All Trial Claims",
    "adm_trial_reset_claims_done": "✅ Reset {count} trial claim(s).",
    "trial_limit_reached": "🎁 Free trial is no longer available.",
    "trial_referral_requirement_line": "👥 Referral requirement: {required} credit(s) ({available} available)",
    "trial_referral_requirement_needed": "👥 You need {required} referral credit(s) to claim the free trial. You currently have {available}.",
    "subs_list_header": "📋 *Your Subscriptions:*\n\nSelect a subscription to view details.",
    "sub_delete_confirm": "🗑️ Are you sure you want to delete this subscription?\n\nThis action cannot be undone.",
    "regen_confirm": "⚠️ This will generate a new subscription link. Your old link will stop working immediately.\n\nAre you sure?",
    "regen_success": "✅ Your subscription link has been regenerated!\n\n🔗 New Link: `{url}`\n\nImport this link into your VPN app.",
    "regen_fail": "❌ Failed to regenerate subscription link. Please try again later.",
    "adm_plan_name_prompt": "📦 *Create Plan*\n\nEnter plan name:",
    "adm_plan_data_prompt": "Enter data limit in GB (e.g. 30):",
    "adm_plan_days_prompt": "Enter duration in days (e.g. 30):",
    "adm_plan_ip_prompt": "Enter IP limit (e.g. 1):",
    "adm_plan_nodes_prompt": "Select nodes for this plan:",
    "adm_enter_price": "Enter new price:",
    "adm_enter_name": "Enter new name:",
    "adm_sub_comment_prompt": "Enter subscription comment (username or name):",
    "adm_sub_data_prompt": "Enter data GB (0 for unlimited):",
    "adm_sub_days_prompt": "Enter duration in days (0 for no expiry):",
    "adm_sub_ip_prompt": "Enter IP limit (0 for unlimited):",
    "adm_sub_nodes_prompt": "Select nodes:",
    "adm_sub_note_prompt": "Enter a note for this subscription (optional):",
    "paid_note_prompt": "Enter a default note for paid subscriptions (send - to remove):\nCurrent: {current}",
    "btn_subs_bulk_note": "📝 Set Note",
    "subs_bulk_note_title": "📝 *Set Note on Subscriptions*\n\nSelect subscriptions to apply a note to:",
    "subs_bulk_note_input": "Type the note text to apply:",
    "subs_bulk_note_done": "✅ Note applied to {count} subscription(s).",
    "adm_user_search_prompt": "Enter user ID or @username to search:",
    "adm_no_users": "No users found.",
    "adm_search_results": "Search results:",
    "adm_user_not_found": "User not found.",
    "adm_no_orders": "No orders found.",
    "adm_orders_count": "Orders ({count}):",
    "adm_already_processed": "Already processed.",
    "adm_admin_id_prompt": "Enter Telegram user ID of the new admin:",
    "adm_admin_perms_prompt": "Enter permissions (comma-separated: view, manage_subs, manage_plans, manage_users, superadmin):",
    "adm_cannot_remove_root": "Cannot remove root admin.",
    "adm_settings_title": "⚙️ *Settings*",
    "adm_gg_url_prompt": "Current: `{current}`\n\nEnter new GhostGate URL:",
    "adm_enter_card_num": "Enter new card number:",
    "adm_enter_card_name": "Enter cardholder name:",
    "adm_enter_crypto_mid": "Enter Cryptomus Merchant ID:",
    "adm_enter_crypto_key": "Enter Cryptomus API Key:",
    "adm_enter_gp_url": "Enter GhostPayments base URL (e.g. https://pay.example.com/SECRET_PATH):",
    "adm_enter_gp_key": "Enter GhostPayments API key (X-GhostPay-Key):",
    "ghostpayments_currency_mismatch": "GhostPayments token `{token}` has no configured currency/rate. Add it in Currencies or change token.",
    "adm_support_prompt": "Current: {current}\n\nEnter support @username:",
    "adm_sync_prompt": "Current: {current}s\n\nEnter sync interval in seconds:",
    "adm_plan_pagination_title": "📄 *Plans Pagination*\n\nConsumer /plans page size: `{consumer}`\nAdmin plans page size: `{admin}`\n\nSet values from 1 to 50.",
    "adm_plan_page_size_consumer_btn": "✏️ /plans Page Size",
    "adm_plan_page_size_admin_btn": "✏️ Admin Plans Page Size",
    "adm_plan_page_size_consumer_prompt": "Current /plans page size: {current}\n\nEnter new value (1-50):",
    "adm_plan_page_size_admin_prompt": "Current admin plans page size: {current}\n\nEnter new value (1-50):",
    "adm_update_http_proxy_prompt": "Current updater HTTP proxy: `{current}`\n\nEnter new updater HTTP proxy URL.\nSend `-` to clear.",
    "adm_update_https_proxy_prompt": "Current updater HTTPS proxy: `{current}`\n\nEnter new updater HTTPS proxy URL.\nSend `-` to clear.",
    "adm_currency_not_found": "Currency not found.",
    "adm_no_currencies_configured": "No currencies configured.",
    "adm_sub_search_prompt": "Enter subscription ID or comment to search:",
    "adm_no_subs_found": "No subscriptions found.",
    "adm_cancelled": "❌ Cancelled.",
    "adm_active": "✅ Active",
    "adm_inactive": "❌ Inactive",
    "adm_disabled": "❌ Disabled",
    "adm_banned": "🚫 Banned",
    "adm_unlimited": "Unlimited",
    "adm_no_expiry": "No Expiry",
    "adm_sub_detail": "📋 *Subscription*\nID: `{sub_id}`\nComment: {comment}\nData: {data_used:.2f} GB / {data_total}\nExpires: {expire}\nStatus: {status}",
    "adm_user_detail": "👤 *User*\nName: {name}\nUsername: {username}\nTelegram ID: `{telegram_id}`\nStatus: {status}\nJoined: {joined}",
    "adm_order_detail": "💰 *Order*\nID: `{order_id}`\nUser: {user}\nPlan: {plan}\nAmount: {amount}\nMethod: {method}\nStatus: {status}\nCreated: {created}",
    "adm_plan_status": "Status: {status}",
    "btn_set_gp_pairs": "⚙️ GP Pairs & Rates",
    "adm_gp_pairs_title": "⚙️ *GhostPayments Pairs*\n\nEnable networks/tokens and set conversion rates:",
    "adm_gp_pair_detail": "⚙️ *{chain}/{token}*\n\nStatus: {status}\nRate: 1 {base} = {rate} {token}",
    "adm_gp_pair_rate_prompt": "1 {token} = ? {base}\n\n(e.g. enter 40000 if 1 USDT = 40,000 IRT):",
    "adm_gp_pair_rate_updated": "✅ Rate updated for {chain}/{token}.",
    "adm_gp_pair_no_rate": "(not set)",
    "gp_pair_select_title": "🪙 *Select network & token for payment:*",
    "ghostpayments_no_rate": "⚠️ No conversion rate set for {chain}/{token}. Configure it in Settings → Crypto Providers → GP Pairs & Rates.",
    "btn_adm_offers": "🎉 Offers",
    "adm_offers_title": "🎉 *Offers*\n\n{list}",
    "adm_offer_none": "(no offers)",
    "adm_offer_item": "• *{name}* — {pct}% off | Plans: {plan_count} | {status}",
    "adm_offer_add_btn": "➕ Add Offer",
    "adm_offer_name_prompt": "Enter offer name:",
    "adm_offer_pct_prompt": "Enter discount % for this offer (e.g. 15):",
    "adm_offer_plans_prompt": "Select which plans this offer applies to (leave empty = all plans):",
    "adm_offer_created": "✅ Offer '{name}' created.",
    "adm_offer_deleted": "🗑️ Offer deleted.",
    "offer_applied": "🎉 Offer applied: -{pct}%",
    "btn_adm_discounts": "🏷️ Discount Codes",
    "adm_discounts_title": "🏷️ *Discount Codes*\n\n{list}",
    "adm_discount_none": "(none)",
    "adm_discount_item": "• `{code}` — {pct}% off (max {max_amount}) | {uses}/{max_uses} uses | Plans: {plans} | {status}",
    "adm_discount_add_btn": "➕ Add Code",
    "adm_discount_code_prompt": "Enter discount code (letters/digits only):",
    "adm_discount_pct_prompt": "Enter discount % (e.g. 20 for 20% off):",
    "adm_discount_max_uses_prompt": "Max uses (0 = unlimited):",
    "adm_discount_plans_prompt": "Select plans this code applies to (empty = all plans):",
    "adm_discount_max_amount_prompt": "Max discount amount (0 = no limit):",
    "adm_discount_created": "✅ Discount code `{code}` created.",
    "adm_discount_invalid_code": "❌ Invalid code. Use only letters and digits.",
    "adm_discount_exists": "❌ Code already exists.",
    "adm_discount_deleted": "🗑️ Discount code deleted.",
    "adm_all_plans": "All",
    "discount_wrong_plan": "❌ This discount code is not valid for this plan.",
    "btn_discount_use": "🏷️ Use Discount Code",
    "btn_discount_applied": "🏷️ Code Applied ({pct}% off)",
    "discount_code_prompt": "🏷️ Enter discount code (or send - to skip):",
    "discount_applied": "🏷️ Discount applied: -{pct}% → {price}",
    "discount_invalid": "❌ Invalid or expired discount code.",
    "discount_exhausted": "❌ This discount code has been used up.",
    "btn_sub_reset_traffic": "🔄 Reset Traffic",
    "sub_traffic_reset": "✅ Traffic reset successfully.",
    "sub_traffic_reset_fail": "❌ Failed to reset traffic.",
    "btn_adm_logs": "📜 Action Logs",
    "adm_logs_title": "📜 *Admin Logs*\n\n{entries}",
    "adm_logs_empty": "(no logs yet)",
    "adm_log_entry": "• [{created_at}] Admin `{admin_id}`: `{action}`{details}",
    "btn_set_start_msg": "👋 Start Message",
    "adm_start_msg_prompt": "Enter custom /start message (send - to use default):\nCurrent: {current}",
    "btn_consumer_referral": "👥 Referrals",
    "referral_panel": "👥 *Referral Program*\n\n🔗 Your link: `{link}`\n\n✅ Successful referrals: {earned}\n💎 Credits used: {used}\n⭐ Available credits: {available}\n\nInvite friends to start the bot and join required channels to earn credits.\nRedeem credits for free VPN subscriptions below!",
    "referral_no_packages": "No referral packages available right now.",
    "referral_packages_header": "🎁 *Available Packages:*\n\nSelect a package to redeem:",
    "referral_pkg_item": "🎁 {name} — {credits} credit(s)",
    "referral_pkg_detail": "🎁 *{name}*\n\n💾 Data: {data_text}\n📅 Duration: {days_text}\n📱 IP Limit: {ip_text}\n⭐ Credits required: {credits}\n\nYour available credits: {available}",
    "referral_pkg_not_enough": "❌ You need {credits} credits to redeem this package. You have {available}.",
    "referral_pkg_confirm": "Confirm redemption of *{name}* for {credits} credit(s)?",
    "referral_redeemed": "✅ Referral package redeemed!\n\n🔗 Link: `{url}`\n\nImport this link into your VPN app.",
    "referral_redeem_fail": "❌ Failed to create subscription. Please try again.",
    "referral_pkg_unavailable": "❌ This package is no longer available.",
    "referral_credited": "🎉 Someone joined using your referral link! You now have {available} available credit(s).",
    "btn_referral_redeem": "🎁 Redeem Packages",
    "btn_referral_back": "⬅️ Back to Referrals",
    "referral_disabled": "👥 Referral program is not available at the moment.",
    "adm_referral_title": "👥 *Referral System*\n\nStatus: {status}\n\nPackages:\n{packages}",
    "adm_referral_pkg_item": "• *{name}* — {credits} credit(s) | {data} GB / {days}d / {ip} IP | {status}",
    "adm_referral_pkg_none": "(no packages)",
    "adm_referral_add_pkg": "➕ Add Package",
    "adm_referral_pkg_name_prompt": "Enter package name:",
    "adm_referral_pkg_credits_prompt": "Enter number of referral credits required to redeem:",
    "adm_referral_pkg_data_prompt": "Enter data limit in GB (0 for unlimited):",
    "adm_referral_pkg_days_prompt": "Enter duration in days (0 for no expiry):",
    "adm_referral_pkg_ip_prompt": "Enter IP limit (0 for unlimited):",
    "adm_referral_pkg_nodes_prompt": "Select nodes for this referral package:",
    "adm_referral_pkg_created": "✅ Referral package created.",
    "adm_referral_pkg_deleted": "🗑️ Referral package deleted.",
    "btn_set_referral": "👥 Referral System",
    "adm_referral_pkg_detail": "🎁 *{name}*\n\n💾 Data: {data_text}\n📅 Duration: {days_text}\n📱 IP Limit: {ip_text}\n⭐ Credits required: {credits}\nStatus: {status}",
    "adm_referral_bulk_nodes_select_pkgs_prompt": "Select referral packages for node update:",
    "adm_referral_pkg_nodes_bulk_done": "✅ Nodes updated for {count} packages.",
    "btn_adm_broadcast": "📢 Broadcast",
    "adm_broadcast_prompt": "Send the message to broadcast to all users (supports Markdown):",
    "adm_broadcast_done": "✅ Broadcast sent to {sent}/{total} users.",
    "btn_adm_notifications": "🔔 Notifications",
    "adm_notifications_title": "🔔 *Admin Notifications*\n\nToggle events to receive admin pings for.",
    "adm_notif_sub_start_msg_prompt": "Enter message to send users when their subscription starts being used (send - to use default):\nCurrent: {current}",
    "adm_notif_sub_start_msg_default": "▶️ Your subscription has started being used!",
    "notif_label_discount": "🏷️ Discount Code",
    "notif_label_payment_link": "🔗 Payment Link",
    "notif_label_purchase": "💰 Purchase",
    "notif_label_trial": "🎁 Trial",
    "notif_label_sub_start": "▶️ Sub First Used",
    "notif_btn_sub_start_msg": "✏️ Sub-start message",
    "btn_wallet_adjust": "💳 Wallet",
    "adm_wallet_title": "💳 *Wallet*\nBalance: *{balance}*",
    "adm_wallet_add_prompt": "Enter amount to add to wallet:",
    "adm_wallet_remove_prompt": "Enter amount to remove (current balance: {balance}):",
    "adm_wallet_adjusted": "✅ Done. New balance: {balance}",
    "adm_wallet_invalid": "❌ Invalid amount.",
    "adm_wallet_insufficient": "❌ Insufficient balance.",
    "btn_wallet_add": "➕ Add Credits",
    "btn_wallet_remove": "➖ Remove Credits",
    "wallet_info": "💳 Wallet: {balance}",
    "btn_wallet_use": "✅ Using {amount} credits from wallet",
    "btn_wallet_enable": "💳 Use {amount} from wallet",
    "wallet_order_created": "✅ Paid with wallet credits!\n\n🔗 Your subscription: `{url}`",
    "wallet_order_fail": "❌ Failed to create subscription.",
    "btn_consumer_wallet": "💳 Wallet",
    "wallet_panel": "💳 *Wallet*\nBalance: *{balance}*\n\nAdd balance to use in purchases.",
    "wallet_topup_prompt": "Enter the amount you want to add to your wallet:",
    "wallet_topup_invalid": "❌ Invalid amount. Enter a positive number.",
    "wallet_topup_pay_title": "💳 Add *{amount}* to wallet\nChoose payment method:",
    "wallet_topup_confirmed": "✅ *{amount}* added to your wallet!\nNew balance: *{balance}*",
    "wallet_topup_label": "Wallet Top-up",
    "btn_wallet_add_balance": "➕ Add Balance",
    "referral_commission_info": "\n\n*💸 Commission:* {status} | {pct}%",
    "btn_referral_commission_toggle": "💸 Toggle Commission",
    "btn_referral_commission_set_pct": "⚙️ Set Commission %",
    "adm_referral_commission_prompt": "Enter commission percentage (e.g. 10 for 10%):",
    "referral_commission_earned": "💸 You earned *{amount}* wallet credits from a referral purchase!",
    "adm_users_list": "👥 *Users* ({total} total, page {page}/{pages})\n\n",
}

_FA = {
    "welcome": "👋 خوش آمدید!\n\nاز منوی زیر پلان‌ها را مشاهده یا وضعیت اشتراک خود را بررسی کنید.",
    "banned": "شما از استفاده از این ربات محروم شده‌اید.",
    "no_plans": "در حال حاضر پلانی موجود نیست. لطفاً بعداً بررسی کنید.",
    "plans_header": "📦 *پلان‌های موجود:*",
    "no_active_subs": "شما اشتراک فعالی ندارید. از /plans برای خرید استفاده کنید.",
    "sub_removed": "❌ اشتراک منقضی یا حذف شده است.",
    "support_contact": "💬 برای پشتیبانی با {support} تماس بگیرید.",
    "support_no_contact": "💬 برای پشتیبانی با مدیر ربات تماس بگیرید.",
    "support_purchase": "\n\nبرای خرید با {support} تماس بگیرید.",
    "support_purchase_no_contact": "\n\nبرای خرید با پشتیبانی تماس بگیرید.",
    "plan_detail": "📦 *{name}*\n\n💾 حجم: {data_text}\n📅 مدت: {days_text}\n📱 محدودیت IP: {ip_text}",
    "plan_price_line_card": "💳 کارت: {price}",
    "plan_price_line_crypto": "🪙 رمزارز: {price}",
    "plan_price_line_request": "🙋 درخواست: {price}",
    "plan_price_line_manual": "🧾 پرداخت دستی: {price}",
    "plan_price_fallback": "💰 قیمت: {price}",
    "card_payment_info": "💳 مبلغ *{price}* را به کارت زیر واریز کنید.\nشماره کارت:\n`{card_number}`\nنام: *{card_holder}*\n\nپس از پرداخت، تصویر رسید خود را ارسال کنید.",
    "receipt_received": "رسید دریافت شد! ⏳ در انتظار تأیید مدیر.",
    "receipt_caption": "📩 رسید جدید\n\n👤 {first_name} ({username})\n🆔 {telegram_id}\n📦 پلان: {plan_name}\n💰 مبلغ: {amount}",
    "sub_confirmed": "✅ اشتراک شما تأیید شد!\n\n🔗 لینک: `{url}`\n\nاین لینک را در اپلیکیشن VPN خود وارد کنید.",
    "sub_rejected": "❌ پرداخت شما رد شد. اگر اشتباهی رخ داده، با پشتیبانی تماس بگیرید.",
    "request_created": "🙋 درخواست اشتراک شما ثبت شد. یک مدیر به زودی آن را بررسی می‌کند.",
    "request_caption": "🙋 درخواست اشتراک\n\n👤 {first_name} ({username})\n🆔 {telegram_id}\n📦 پلان: {plan_name}\n📝 دلیل: {reason}",
    "request_no_reason": "(بدون دلیل)",
    "request_approved": "✅ درخواست اشتراک شما تأیید شد!\n\n🔗 لینک: `{url}`\n\nاین لینک را در اپلیکیشن VPN خود وارد کنید.",
    "request_declined": "❌ درخواست اشتراک شما رد شد.",
    "manual_request_created": "🧾 درخواست پرداخت دستی ارسال شد. مدیر آن را تایید یا رد می‌کند.",
    "manual_request_caption": "🧾 درخواست پرداخت دستی\n\n👤 {first_name} ({username})\n🆔 {telegram_id}\n📦 پلان: {plan_name}\n💰 مبلغ: {amount}",
    "manual_chain_prompt": "🧾 *پرداخت دستی USDT*\n\nشبکه مورد نظر خود را انتخاب کنید:",
    "manual_send_proof": "شبکه: *{chain}*\nمبلغ: *{amount}*\nآدرس:\n`{address}`\n\nبعد از پرداخت، هش تراکنش را ارسال کنید:",
    "manual_proof_received": "✅ هش تراکنش دریافت شد. مدیر بررسی و تایید/رد می‌کند.",
    "manual_no_address": "پرداخت دستی USDT هنوز پیکربندی نشده است.",
    "crypto_invoice_created": "🪙 پرداخت با رمزارز\n\nمبلغ: {amount}\n\nبرای پرداخت روی دکمه زیر کلیک کنید.",
    "crypto_paid": "✅ پرداخت رمزارزی تأیید شد!\n\n🔗 لینک: `{url}`\n\nاین لینک را در اپلیکیشن VPN خود وارد کنید.",
    "service_unavailable": "⚠️ سرویس موقتاً در دسترس نیست. لطفاً دوباره امتحان کنید.",
    "sub_orphaned": "⚠️ اشتراک شما از سرور حذف شده است. لطفاً با پشتیبانی تماس بگیرید.",
    "admin_confirmed": "✅ تأیید شد توسط {admin}\nشناسه اشتراک: {sub_id}",
    "admin_rejected": "❌ رد شد توسط {admin}",
    "wizard_step1": "⚙️ *راه‌اندازی اولیه*\n\nمرحله ۱/۴ — آدرس GhostGate\n\nآدرس کامل پنل شامل مسیر مخفی را وارد کنید.\nمثال: `https://vpn.example.com/mySecretPath`",
    "wizard_step1_fail": "❌ خطا در اتصال: {error}\n\nدوباره امتحان کنید:",
    "wizard_step2": "مرحله ۲/۴ — تماس پشتیبانی\n\nیک @username برای پشتیبانی کاربران وارد کنید. (مثال: @support)",
    "wizard_step3a": "مرحله ۳/۴ — پرداخت کارت به کارت\n\nشماره کارت را وارد کنید (مثال: ۶۰۳۷-۹۹۷۵-XXXX-XXXX):",
    "wizard_step3b": "نام صاحب کارت را وارد کنید:",
    "wizard_step3c": "مرحله ۳/۴ — Cryptomus (اختیاری)\n\nMerchant ID خود را وارد کنید:",
    "wizard_step3d": "API Key خود را وارد کنید:",
    "wizard_step4": "مرحله ۴/۴ — ارز پایه\n\nکد ارز پایه را وارد کنید (مثال: IRT، USD، USDT):\nقیمت پلان‌ها با این واحد وارد می‌شود.",
    "wizard_done": "✅ راه‌اندازی کامل شد!\n\nمی‌توانید ارزهای بیشتر با نرخ تبدیل را از تنظیمات → ارزها اضافه کنید.",
    "btn_skip": "⏭️ رد کردن",
    "btn_back": "⬅️ بازگشت",
    "btn_done": "✅ انجام شد",
    "btn_cancel": "❌ لغو",
    "btn_buy_plan": "🛒 خرید {name}",
    "btn_select_all": "✅ انتخاب همه",
    "btn_unselect_all": "⬜ حذف انتخاب همه",
    "btn_join_channel": "📢 عضویت در کانال",
    "btn_i_have_joined": "✅ عضو شدم",
    "btn_yes": "✅ بله",
    "btn_no": "❌ خیر",
    "btn_delete": "🗑️ حذف",
    "btn_move_up": "⬆️ انتقال به بالا",
    "btn_move_down": "⬇️ انتقال به پایین",
    "btn_confirm": "✅ تایید",
    "btn_reject": "❌ رد",
    "btn_adm_subs": "📋 اشتراک‌ها",
    "btn_adm_plans": "🗂️ پلان‌ها",
    "btn_adm_users": "👥 کاربران",
    "btn_adm_admins": "👑 مدیران",
    "btn_adm_orders": "💰 سفارشات",
    "btn_adm_settings": "⚙️ تنظیمات",
    "btn_adm_update": "🔄 بروزرسانی ربات",
    "btn_set_gg": "🔗 اتصال GhostGate",
    "btn_set_card": "💳 کارت به کارت",
    "btn_set_crypto": "🪙 ارائه‌دهنده‌های کریپتو",
    "btn_set_requests": "🙋 جریان درخواست",
    "btn_set_support": "📝 راه ارتباط پشتیبانی",
    "btn_set_currencies": "💱 ارزها",
    "btn_set_trial": "🎁 اشتراک آزمایشی",
    "btn_set_paid_note": "📝 یادداشت اشتراک پرداختی",
    "btn_set_usdt": "🧾 آدرس‌های USDT",
    "btn_set_sync": "🔄 فاصله همگام‌سازی",
    "btn_set_plans_pagination": "📄 صفحه‌بندی پلان‌ها",
    "btn_set_force_join": "📢 اجبار عضویت کانال",
    "btn_set_plan_start_after_use": "⏱️ شروع انقضای پلان از اولین استفاده",
    "btn_set_trial_start_after_use": "🎁 شروع انقضای تست از اولین استفاده",
    "btn_set_update_http_proxy": "🌐 پروکسی HTTP آپدیت",
    "btn_set_update_https_proxy": "🔐 پروکسی HTTPS آپدیت",
    "btn_curr_add": "➕ افزودن ارز",
    "btn_curr_set_base": "📌 تنظیم پایه",
    "btn_method_card": "💳 کارت",
    "btn_method_crypto": "🪙 رمزارز",
    "btn_method_request": "🙋 درخواست",
    "btn_method_manual": "🧾 دستی",
    "btn_sub_stats": "📊 آمار و QR",
    "btn_sub_configs": "🔗 کانفیگ‌های نود",
    "btn_ban": "🚫 مسدود",
    "btn_unban": "🔓 رفع مسدودی",
    "btn_reset_trial": "🔄 ریست تست",
    "adm_trial_reset_user_done": "✅ تست این کاربر ریست شد.",
    "adm_trial_no_claim": "ℹ️ این کاربر تستی دریافت نکرده.",
    "btn_activate": "✅ فعال‌سازی",
    "btn_deactivate": "❌ غیرفعالسازی",
    "btn_edit_price": "✏️ ویرایش قیمت",
    "btn_edit_name": "✏️ ویرایش نام",
    "btn_edit_nodes": "🖥️ ویرایش نودها",
    "btn_edit_rate": "✏️ ویرایش نرخ",
    "btn_edit_card_num": "✏️ ویرایش شماره کارت",
    "btn_edit_card_name": "✏️ ویرایش نام دارنده",
    "btn_edit_mid": "✏️ Merchant ID کریپتوموس",
    "btn_edit_api_key": "✏️ API Key کریپتوموس",
    "btn_edit_gp_url": "✏️ آدرس GhostPayments",
    "btn_edit_gp_key": "✏️ کلید API GhostPayments",
    "btn_consumer_plans": "📦 پلان‌ها",
    "btn_consumer_status": "📊 وضعیت من",
    "btn_consumer_support": "💬 پشتیبانی",
    "btn_consumer_trial": "🎁 آزمایشی رایگان",
    "btn_trial_claim": "🎁 دریافت آزمایشی",
    "btn_regen_link": "🔄 تجدید لینک",
    "btn_sub_disable": "⛔ غیرفعال‌سازی",
    "btn_sub_enable": "✅ فعال‌سازی",
    "sub_disabled": "⛔ اشتراک غیرفعال شد.",
    "sub_enabled": "✅ اشتراک مجدداً فعال شد.",
    "sub_toggle_fail": "❌ بروزرسانی اشتراک ناموفق بود.",
    "crypto_paid_admin": "💰 *پرداخت رمزارز دریافت شد*\n\n👤 {first_name} ({username})\n🆔 {telegram_id}\n📦 پلان: {plan_name}\n💰 مبلغ: {amount} {currency}",
    "btn_pay_card": "💳 پرداخت کارت به کارت",
    "btn_pay_crypto": "🪙 پرداخت با رمزارز",
    "btn_request_sub": "🙋 ثبت درخواست اشتراک",
    "btn_pay_manual": "🧾 USDT (TRC20/BSC/POL)",
    "btn_open_payment": "💳 صفحه پرداخت",
    "adm_enabled": "✅ فعال",
    "adm_toggle_btn": "تغییر وضعیت: {status}",
    "adm_requests_title": "🙋 *جریان درخواست*",
    "adm_user_orders_title": "📋 سفارشات کاربر:",
    "adm_orders_title": "💰 *سفارشات*\n\n⏳ در انتظار: {count}",
    "adm_orders_pending_waiting": "⏳ درانتظار/درحال بررسی",
    "adm_orders_paid": "✅ پرداخت‌شده",
    "adm_orders_rejected": "❌ ردشده",
    "adm_admins_title": "👑 *مدیران*\nمدیر اصلی: `{root_id}`",
    "adm_add_admin_btn": "➕ افزودن مدیر",
    "adm_remove_btn": "🗑️ حذف",
    "adm_create_plan_btn": "➕ ایجاد پلان",
    "adm_bulk_create_btn": "📊 ساخت گروهی از جدول",
    "adm_bulk_nodes_btn": "🖥️ ویرایش گروهی نودها",
    "adm_bulk_delete_btn": "🗑️ حذف گروهی پلان‌ها",
    "adm_bulk_delete_prompt": "پلان‌هایی که می‌خواهید حذف شوند را انتخاب کنید:",
    "adm_bulk_delete_done": "✅ {count} پلان حذف شد.",
    "adm_bulk_enable_btn": "✅ فعال‌سازی گروهی پلان‌ها",
    "adm_bulk_disable_btn": "❌ غیرفعال‌سازی گروهی پلان‌ها",
    "adm_bulk_enable_prompt": "پلان‌هایی که می‌خواهید فعال شوند را انتخاب کنید:",
    "adm_bulk_disable_prompt": "پلان‌هایی که می‌خواهید غیرفعال شوند را انتخاب کنید:",
    "adm_bulk_enable_done": "✅ {count} پلان فعال شد.",
    "adm_bulk_disable_done": "❌ {count} پلان غیرفعال شد.",
    "adm_bulk_price_multiply_btn": "✖️ ضرب گروهی قیمت‌ها",
    "adm_bulk_price_divide_btn": "➗ تقسیم گروهی قیمت‌ها",
    "adm_bulk_price_select_plans": "پلان‌هایی که می‌خواهید قیمتشان تغییر کند را انتخاب کنید:",
    "adm_bulk_price_factor_prompt": "ضریب تغییر را وارد کنید (مثلاً ۱.۱ برای ۱۰٪ افزایش، ۰.۹ برای ۱۰٪ کاهش، ۲ برای دو برابر):",
    "adm_bulk_price_done": "✅ قیمت {count} پلان بروزرسانی شد.",
    "adm_bulk_nodes_select_plans_prompt": "پلان‌هایی که نودهایشان باید تغییر کند را انتخاب کنید:",
    "adm_bulk_create_nodes_prompt": "نودهای مشترک برای همه پلان‌های تولیدی را انتخاب کنید:",
    "adm_bulk_create_matrix_prompt": "جدول قیمت ماهانه را (انعطاف‌پذیر) بفرستید:\n`10: p1,p2,p3,p4`\n`20 p1 p2 p3 p4`\n`1000|p1|p2|p3|p4`\n\nمقدار اول=حجم(GB یا TB). ستون‌های بعد=IP1..IPN.\nبرای IRT می‌توانید `k` بزنید (مثل 80k). روزها ثابت 30 است.",
    "adm_bulk_create_bad_data": "ردیف‌های حجم نامعتبر یا ناقص هستند.",
    "adm_bulk_create_bad_price": "قیمت‌ها نامعتبرند یا تعداد ستون‌های IP یکسان نیست.",
    "adm_bulk_create_done": "✅ پلان‌های گروهی ذخیره شدند.\nایجاد: {created}\nبروزرسانی: {updated}",
    "adm_plan_nodes_edit_prompt": "نودهای این پلان را انتخاب کنید:",
    "adm_plan_nodes_bulk_prompt": "نودهایی را انتخاب کنید که برای همه پلان‌ها اعمال شوند:",
    "adm_plan_nodes_bulk_done": "✅ نودها برای {count} پلان بروزرسانی شد.",
    "irt_price_step": "برای IRT قیمت باید حداقل 1000 و با گام 1000 باشد.",
    "adm_search_btn": "🔍 جستجو",
    "adm_create_btn": "➕ ایجاد",
    "adm_search_user_btn": "🔍 جستجوی کاربر",
    "adm_trial_set_data": "✏️ تنظیم حجم گیگ",
    "adm_trial_set_expire": "✏️ تنظیم زمان انقضا",
    "adm_trial_set_nodes": "🖥️ تنظیم نودها",
    "adm_trial_set_note": "📝 تنظیم یادداشت",
    "trial_note_prompt": "یادداشت اشتراک آزمایشی را وارد کنید (برای حذف - بفرستید):\nفعلی: {current}",
    "adm_trial_nodes_prompt": "🎁 نودهای اشتراک آزمایشی را انتخاب کنید:",
    "adm_update_checking": "🔄 در حال بررسی بروزرسانی...",
    "adm_update_none": "✅ ربات بروز است.",
    "adm_update_starting": "⬇️ شروع بروزرسانی به {version}...",
    "adm_update_failed": "❌ بروزرسانی ناموفق بود. لاگ را بررسی کنید.",
    "adm_force_join_title": "📢 *اجبار عضویت کانال*\n\nوضعیت: {status}\n\nکانال‌ها:\n{channels}",
    "adm_force_join_set_channel": "➕ افزودن کانال",
    "adm_force_join_prompt": "یوزرنیم یا آی‌دی کانال را بفرستید (مثل `@mychannel` یا `-100...`).",
    "adm_force_join_no_channels": "(هیچ)",
    "adm_force_join_remove_btn": "🗑️ حذف {channel}",
    "adm_plan_after_use_status": "⏱️ انقضای پلان از اولین استفاده: {status}",
    "adm_trial_after_use_status": "🎁 انقضای تست از اولین استفاده: {status}",
    "force_join_required": "برای استفاده از ربات ابتدا باید عضو {channel} شوید.",
    "force_join_alert": "ابتدا عضو کانال اجباری شوید.",
    "adm_usdt_title": "🧾 *پرداخت دستی USDT*\n\nوضعیت: {status}\n\nTRC20: `{trc20}`\nBSC: `{bsc}`\nPOLYGON: `{polygon}`",
    "adm_usdt_rate_prompt": "۱ USDT = ? {base} برای {chain}\n\n(مثال: ۱۶۸۰۰۰ اگر ۱ USDT = ۱۶۸٬۰۰۰ تومان باشد):",
    "adm_enter_usdt_trc20": "آدرس USDT شبکه TRC20 را وارد کنید:",
    "adm_enter_usdt_bsc": "آدرس USDT شبکه BSC را وارد کنید:",
    "adm_enter_usdt_polygon": "آدرس USDT شبکه POLYGON را وارد کنید:",
    "admin_menu_title": "👑 *پنل مدیریت*\nنسخه: `{version}`",
    "plans_title": "🗂️ *پلان‌ها*\n\nیک پلان را برای مدیریت انتخاب کنید:",
    "plans_page_info": "صفحه {page}/{pages}",
    "no_plans_admin": "هنوز پلانی ایجاد نشده.",
    "plan_created": "✅ پلان ایجاد شد.",
    "plan_deleted": "🗑️ پلان حذف شد.",
    "setting_saved": "✅ تنظیم ذخیره شد.",
    "enter_value": "مقدار جدید را وارد کنید:",
    "sub_created_admin": "✅ اشتراک ایجاد شد.\nشناسه: {sub_id}\nلینک: `{url}`",
    "sub_deleted": "🗑️ اشتراک حذف شد.",
    "user_banned": "🚫 کاربر مسدود شد.",
    "user_unbanned": "🔓 کاربر مسدودیت‌زدایی شد.",
    "admin_added": "✅ مدیر اضافه شد.",
    "admin_removed": "🗑️ مدیر حذف شد.",
    "invalid_input": "❌ ورودی نامعتبر. لطفاً دوباره امتحان کنید.",
    "order_not_found": "سفارش یافت نشد.",
    "ghostgate_error": "❌ ارتباط با GhostGate ناموفق بود. دوباره امتحان کنید.",
    "reason_prompt": "آیا می‌خواهید دلیلی وارد کنید؟ تایپ کنید یا رد کردن را بزنید:",
    "reject_reason_prompt": "دلیل رد را وارد کنید (یا رد کردن را بزنید):",
    "reject_notif": "❌ پرداخت شما رد شد.\n\nدلیل: {reason}",
    "curr_title": "💱 *ارزها*\nپایه: {base}\n\nیک ارز را برای مدیریت انتخاب کنید:",
    "curr_no_currencies": "💱 *ارزها*\nپایه: {base}\n\nهنوز ارز اضافه‌ای پیکربندی نشده.",
    "curr_detail": "💱 *{code}* — {name}\nاعشار: {decimals}\nروش‌ها: {methods}\nنرخ: ۱ {base} = {rate} {code}",
    "curr_add_code": "کد ارز را وارد کنید (مثال: IRT، USDT، USD):",
    "curr_add_name": "نام نمایشی را وارد کنید (مثال: تومان، تتر، دلار):",
    "curr_add_decimals": "تعداد اعشار را وارد کنید (۰ برای تومان، ۲ برای تتر):",
    "curr_add_methods": "روش‌های پرداختی که از این ارز استفاده می‌کنند را انتخاب کنید:",
    "curr_add_rate_prompt": "۱ {code} = ? {base}\n\n(مثال: ۴۰۰۰۰ اگر ۱ USDT = ۴۰٬۰۰۰ تومان باشد):",
    "curr_added": "✅ ارز {code} اضافه شد.",
    "curr_deleted": "🗑️ ارز حذف شد.",
    "curr_rate_updated": "✅ نرخ به‌روزرسانی شد.",
    "curr_set_base_prompt": "ارزی که قیمت پلان‌ها با آن وارد می‌شود را انتخاب کنید:",
    "curr_base_set": "✅ ارز پایه به {code} تغییر کرد.",
    "plan_price_enter": "قیمت را به {base} وارد کنید (مثال: ۵۰۰۰۰۰):",
    "trial_info": "🎁 *آزمایشی رایگان*\n\n{data_gb} گیگ • {expire_h} ساعت\n{start_text}{requirement_text}\n\nاشتراک آزمایشی یک‌بار مصرف خود را دریافت کنید!",
    "trial_start_from_connection": "اعتبار از اولین اتصال شروع می‌شود.",
    "trial_start_from_get": "اعتبار از همین لحظه شروع می‌شود.",
    "trial_not_available": "🎁 در حال حاضر اشتراک آزمایشی موجود نیست.",
    "trial_already_claimed": "🎁 شما قبلاً اشتراک آزمایشی خود را دریافت کرده‌اید.",
    "trial_claimed": "🎁 اشتراک آزمایشی شما آماده است!\n\n🔗 لینک: `{url}`\n\nاین لینک را در اپلیکیشن VPN وارد کنید. {start_text}",
    "trial_plan_name": "آزمایشی رایگان",
    "trial_settings": "🎁 *اشتراک آزمایشی*\n\nوضعیت: {status}\nحجم: {data_gb} گیگابایت\nانقضا: {expire_h} ساعت\nنودها: {node_count} پیکربندی‌شده{requirement_text}",
    "trial_data_prompt": "حجم آزمایشی را به گیگابایت وارد کنید (مثال: ۰.۵):",
    "trial_expire_prompt": "مدت آزمایشی را به ساعت وارد کنید (مثال: ۲۴، یا ۰.۵ برای ۳۰ دقیقه):",
    "adm_trial_set_disabled_msg": "✏️ تنظیم پیام غیرفعال",
    "adm_trial_disabled_msg_prompt": "پیامی که هنگام غیرفعال بودن تست نمایش داده می‌شود را وارد کنید (برای پیش‌فرض - بفرستید):\nفعلی: {current}",
    "adm_trial_set_max_claims": "🔢 محدودیت تعداد دریافت",
    "adm_trial_max_claims_prompt": "حداکثر تعداد کاربرانی که می‌توانند تست بگیرند را وارد کنید (۰ = نامحدود):\nفعلی: {current}",
    "adm_trial_set_referral_requirement": "👥 تنظیم شرط دعوت",
    "adm_trial_referral_requirement_prompt": "تعداد اعتبار دعوت لازم برای دریافت آزمایشی را وارد کنید (۰ = غیرفعال):\nفعلی: {current}",
    "adm_trial_referral_requirement_status": "👥 شرط دعوت: {required}",
    "adm_trial_reset_claims_btn": "🔄 ریست تمام تست‌ها",
    "adm_trial_reset_claims_done": "✅ {count} تست ریست شد.",
    "trial_limit_reached": "🎁 آزمایشی رایگان دیگر در دسترس نیست.",
    "trial_referral_requirement_line": "👥 شرط دعوت: {required} اعتبار ({available} موجود)",
    "trial_referral_requirement_needed": "👥 برای دریافت آزمایشی رایگان به {required} اعتبار دعوت نیاز دارید. موجودی فعلی شما {available} است.",
    "subs_list_header": "📋 *اشتراک‌های شما:*\n\nیک اشتراک را برای مشاهده جزئیات انتخاب کنید.",
    "sub_delete_confirm": "🗑️ آیا از حذف این اشتراک مطمئن هستید؟\n\nاین عملیات قابل بازگشت نیست.",
    "regen_confirm": "⚠️ این کار یک لینک اشتراک جدید ایجاد می‌کند. لینک قبلی بلافاصله غیرفعال می‌شود.\n\nمطمئنید؟",
    "regen_success": "✅ لینک اشتراک شما تجدید شد!\n\n🔗 لینک جدید: `{url}`\n\nاین لینک را در اپلیکیشن VPN وارد کنید.",
    "regen_fail": "❌ تجدید لینک اشتراک ناموفق بود. لطفاً دوباره امتحان کنید.",
    "adm_plan_name_prompt": "📦 *ایجاد پلان*\n\nنام پلان را وارد کنید:",
    "adm_plan_data_prompt": "محدودیت حجم را به گیگابایت وارد کنید (مثال: ۳۰):",
    "adm_plan_days_prompt": "مدت زمان را به روز وارد کنید (مثال: ۳۰):",
    "adm_plan_ip_prompt": "محدودیت IP را وارد کنید (مثال: ۱):",
    "adm_plan_nodes_prompt": "نودهای این پلان را انتخاب کنید:",
    "adm_enter_price": "قیمت جدید را وارد کنید:",
    "adm_enter_name": "نام جدید را وارد کنید:",
    "adm_sub_comment_prompt": "توضیح اشتراک را وارد کنید (نام کاربری یا نام):",
    "adm_sub_data_prompt": "حجم را به گیگابایت وارد کنید (۰ برای نامحدود):",
    "adm_sub_days_prompt": "مدت زمان را به روز وارد کنید (۰ برای بی‌انقضا):",
    "adm_sub_ip_prompt": "محدودیت IP را وارد کنید (۰ برای نامحدود):",
    "adm_sub_nodes_prompt": "نودها را انتخاب کنید:",
    "adm_sub_note_prompt": "یادداشت را وارد کنید (اختیاری):",
    "paid_note_prompt": "یادداشت پیش‌فرض اشتراک‌های پرداختی را وارد کنید (برای حذف - بفرستید):\nفعلی: {current}",
    "btn_subs_bulk_note": "📝 تنظیم یادداشت",
    "subs_bulk_note_title": "📝 *تنظیم یادداشت روی اشتراک‌ها*\n\nاشتراک‌ها را انتخاب کنید:",
    "subs_bulk_note_input": "متن یادداشت را وارد کنید:",
    "subs_bulk_note_done": "✅ یادداشت برای {count} اشتراک اعمال شد.",
    "adm_user_search_prompt": "شناسه کاربری یا @username را برای جستجو وارد کنید:",
    "adm_no_users": "کاربری یافت نشد.",
    "adm_search_results": "نتایج جستجو:",
    "adm_user_not_found": "کاربر یافت نشد.",
    "adm_no_orders": "سفارشی یافت نشد.",
    "adm_orders_count": "سفارشات ({count}):",
    "adm_already_processed": "قبلاً پردازش شده است.",
    "adm_admin_id_prompt": "شناسه تلگرام مدیر جدید را وارد کنید:",
    "adm_admin_perms_prompt": "دسترسی‌ها را وارد کنید (با ویرگول جدا: view, manage_subs, manage_plans, manage_users, superadmin):",
    "adm_cannot_remove_root": "نمی‌توان مدیر اصلی را حذف کرد.",
    "adm_settings_title": "⚙️ *تنظیمات*",
    "adm_gg_url_prompt": "آدرس فعلی: `{current}`\n\nآدرس جدید GhostGate را وارد کنید:",
    "adm_enter_card_num": "شماره کارت جدید را وارد کنید:",
    "adm_enter_card_name": "نام صاحب کارت را وارد کنید:",
    "adm_enter_crypto_mid": "Merchant ID Cryptomus را وارد کنید:",
    "adm_enter_crypto_key": "API Key Cryptomus را وارد کنید:",
    "adm_enter_gp_url": "آدرس پایه GhostPayments را وارد کنید (مثال: https://pay.example.com/SECRET_PATH):",
    "adm_enter_gp_key": "کلید API GhostPayments (X-GhostPay-Key) را وارد کنید:",
    "ghostpayments_currency_mismatch": "برای توکن `{token}` در GhostPayments ارز/نرخ تعریف نشده است. آن را در بخش ارزها اضافه کنید یا توکن را تغییر دهید.",
    "adm_support_prompt": "آدرس فعلی: {current}\n\n@username پشتیبانی را وارد کنید:",
    "adm_sync_prompt": "مقدار فعلی: {current} ثانیه\n\nبازه همگام‌سازی را به ثانیه وارد کنید:",
    "adm_plan_pagination_title": "📄 *صفحه‌بندی پلان‌ها*\n\nاندازه صفحه /plans کاربر: `{consumer}`\nاندازه صفحه پلان‌های ادمین: `{admin}`\n\nمقدار بین ۱ تا ۵۰ وارد کنید.",
    "adm_plan_page_size_consumer_btn": "✏️ اندازه صفحه /plans",
    "adm_plan_page_size_admin_btn": "✏️ اندازه صفحه پلان‌های ادمین",
    "adm_plan_page_size_consumer_prompt": "اندازه فعلی صفحه /plans: {current}\n\nمقدار جدید را وارد کنید (۱-۵۰):",
    "adm_plan_page_size_admin_prompt": "اندازه فعلی صفحه پلان‌های ادمین: {current}\n\nمقدار جدید را وارد کنید (۱-۵۰):",
    "adm_update_http_proxy_prompt": "پروکسی HTTP آپدیتر فعلی: `{current}`\n\nآدرس جدید پروکسی HTTP آپدیتر را وارد کنید.\nبرای حذف `-` بفرستید.",
    "adm_update_https_proxy_prompt": "پروکسی HTTPS آپدیتر فعلی: `{current}`\n\nآدرس جدید پروکسی HTTPS آپدیتر را وارد کنید.\nبرای حذف `-` بفرستید.",
    "adm_currency_not_found": "ارز یافت نشد.",
    "adm_no_currencies_configured": "هیچ ارزی پیکربندی نشده.",
    "adm_sub_search_prompt": "شناسه اشتراک یا توضیح را برای جستجو وارد کنید:",
    "adm_no_subs_found": "اشتراکی یافت نشد.",
    "adm_cancelled": "❌ لغو شد.",
    "adm_active": "✅ فعال",
    "adm_inactive": "❌ غیرفعال",
    "adm_disabled": "❌ غیرفعال",
    "adm_banned": "🚫 مسدود",
    "adm_unlimited": "نامحدود",
    "adm_no_expiry": "بدون انقضا",
    "adm_sub_detail": "📋 *اشتراک*\nشناسه: `{sub_id}`\nتوضیح: {comment}\nداده: {data_used:.2f} گیگ / {data_total}\nانقضا: {expire}\nوضعیت: {status}",
    "adm_user_detail": "👤 *کاربر*\nنام: {name}\nنام کاربری: {username}\nشناسه تلگرام: `{telegram_id}`\nوضعیت: {status}\nعضویت: {joined}",
    "adm_order_detail": "💰 *سفارش*\nشناسه: `{order_id}`\nکاربر: {user}\nپلان: {plan}\nمبلغ: {amount}\nروش: {method}\nوضعیت: {status}\nتاریخ: {created}",
    "adm_plan_status": "وضعیت: {status}",
    "btn_set_gp_pairs": "⚙️ جفت‌ها و نرخ‌های GP",
    "adm_gp_pairs_title": "⚙️ *جفت‌های GhostPayments*\n\nشبکه‌ها/توکن‌ها را فعال کنید و نرخ تبدیل تنظیم کنید:",
    "adm_gp_pair_detail": "⚙️ *{chain}/{token}*\n\nوضعیت: {status}\nنرخ: ۱ {base} = {rate} {token}",
    "adm_gp_pair_rate_prompt": "۱ {token} = ? {base}\n\n(مثال: ۴۰۰۰۰ اگر ۱ USDT = ۴۰٬۰۰۰ تومان باشد):",
    "adm_gp_pair_rate_updated": "✅ نرخ {chain}/{token} بروزرسانی شد.",
    "adm_gp_pair_no_rate": "(تنظیم نشده)",
    "gp_pair_select_title": "🪙 *شبکه و توکن پرداخت را انتخاب کنید:*",
    "ghostpayments_no_rate": "⚠️ نرخ تبدیل برای {chain}/{token} تنظیم نشده. در تنظیمات → ارائه‌دهنده‌های کریپتو → جفت‌های GP تنظیم کنید.",
    "btn_adm_offers": "🎉 آفرها",
    "adm_offers_title": "🎉 *آفرها*\n\n{list}",
    "adm_offer_none": "(آفری وجود ندارد)",
    "adm_offer_item": "• *{name}* — {pct}٪ تخفیف | پلان‌ها: {plan_count} | {status}",
    "adm_offer_add_btn": "➕ افزودن آفر",
    "adm_offer_name_prompt": "نام آفر را وارد کنید:",
    "adm_offer_pct_prompt": "درصد تخفیف این آفر را وارد کنید (مثال: ۱۵):",
    "adm_offer_plans_prompt": "پلان‌هایی که این آفر روی آن‌ها اعمال می‌شود را انتخاب کنید (بدون انتخاب = همه پلان‌ها):",
    "adm_offer_created": "✅ آفر '{name}' ایجاد شد.",
    "adm_offer_deleted": "🗑️ آفر حذف شد.",
    "offer_applied": "🎉 آفر اعمال شد: -{pct}٪",
    "btn_adm_discounts": "🏷️ کدهای تخفیف",
    "adm_discounts_title": "🏷️ *کدهای تخفیف*\n\n{list}",
    "adm_discount_none": "(هیچ)",
    "adm_discount_item": "• `{code}` — {pct}% تخفیف (حداکثر {max_amount}) | {uses}/{max_uses} استفاده | پلن‌ها: {plans} | {status}",
    "adm_discount_add_btn": "➕ افزودن کد",
    "adm_discount_code_prompt": "کد تخفیف را وارد کنید (فقط حروف و اعداد):",
    "adm_discount_pct_prompt": "درصد تخفیف را وارد کنید (مثال: ۲۰ برای ۲۰٪ تخفیف):",
    "adm_discount_max_uses_prompt": "حداکثر استفاده (۰ = نامحدود):",
    "adm_discount_plans_prompt": "پلن‌هایی که این کد برای آن‌ها معتبر است را انتخاب کنید (خالی = همه پلن‌ها):",
    "adm_discount_max_amount_prompt": "حداکثر مقدار تخفیف (۰ = بدون محدودیت):",
    "adm_discount_created": "✅ کد تخفیف `{code}` ایجاد شد.",
    "adm_discount_invalid_code": "❌ کد نامعتبر. فقط حروف و اعداد مجاز است.",
    "adm_discount_exists": "❌ این کد قبلاً وجود دارد.",
    "adm_discount_deleted": "🗑️ کد تخفیف حذف شد.",
    "adm_all_plans": "همه",
    "discount_wrong_plan": "❌ این کد تخفیف برای این پلن معتبر نیست.",
    "btn_discount_use": "🏷️ استفاده از کد تخفیف",
    "btn_discount_applied": "🏷️ کد اعمال شد ({pct}٪ تخفیف)",
    "discount_code_prompt": "🏷️ کد تخفیف را وارد کنید (یا - برای رد کردن):",
    "discount_applied": "🏷️ تخفیف اعمال شد: -{pct}% → {price}",
    "discount_invalid": "❌ کد تخفیف نامعتبر یا منقضی شده.",
    "discount_exhausted": "❌ این کد تخفیف تمام شده است.",
    "btn_sub_reset_traffic": "🔄 ریست ترافیک",
    "sub_traffic_reset": "✅ ترافیک با موفقیت ریست شد.",
    "sub_traffic_reset_fail": "❌ ریست ترافیک ناموفق بود.",
    "btn_adm_logs": "📜 لاگ اقدامات",
    "adm_logs_title": "📜 *لاگ مدیران*\n\n{entries}",
    "adm_logs_empty": "(هنوز لاگی ندارد)",
    "adm_log_entry": "• [{created_at}] مدیر `{admin_id}`: `{action}`{details}",
    "btn_set_start_msg": "👋 پیام شروع",
    "adm_start_msg_prompt": "پیام سفارشی /start را وارد کنید (برای پیش‌فرض - بفرستید):\nفعلی: {current}",
    "btn_consumer_referral": "👥 دعوت دوستان",
    "referral_panel": "👥 *برنامه دعوت*\n\n🔗 لینک شما: `{link}`\n\n✅ دعوت‌های موفق: {earned}\n💎 اعتبار استفاده‌شده: {used}\n⭐ اعتبار موجود: {available}\n\nدوستانتان را دعوت کنید تا ربات را استارت بزنند و در کانال‌های موردنیاز عضو شوند تا اعتبار کسب کنید.\nاعتبار را با اشتراک VPN رایگان تبادل کنید!",
    "referral_no_packages": "در حال حاضر بسته‌ی دعوتی موجود نیست.",
    "referral_packages_header": "🎁 *بسته‌های موجود:*\n\nیک بسته را برای دریافت انتخاب کنید:",
    "referral_pkg_item": "🎁 {name} — {credits} اعتبار",
    "referral_pkg_detail": "🎁 *{name}*\n\n💾 حجم: {data_text}\n📅 مدت: {days_text}\n📱 محدودیت IP: {ip_text}\n⭐ اعتبار لازم: {credits}\n\nاعتبار موجود شما: {available}",
    "referral_pkg_not_enough": "❌ برای دریافت این بسته به {credits} اعتبار نیاز دارید. شما {available} اعتبار دارید.",
    "referral_pkg_confirm": "آیا مطمئنید که می‌خواهید *{name}* را با {credits} اعتبار دریافت کنید؟",
    "referral_redeemed": "✅ بسته دعوتی دریافت شد!\n\n🔗 لینک: `{url}`\n\nاین لینک را در اپلیکیشن VPN وارد کنید.",
    "referral_redeem_fail": "❌ ایجاد اشتراک ناموفق بود. لطفاً دوباره امتحان کنید.",
    "referral_pkg_unavailable": "❌ این بسته دیگر موجود نیست.",
    "referral_credited": "🎉 کسی از لینک دعوت شما استفاده کرد! اکنون {available} اعتبار موجود دارید.",
    "btn_referral_redeem": "🎁 دریافت بسته",
    "btn_referral_back": "⬅️ بازگشت به دعوت‌ها",
    "referral_disabled": "👥 برنامه دعوت در حال حاضر در دسترس نیست.",
    "adm_referral_title": "👥 *سیستم دعوت*\n\nوضعیت: {status}\n\nبسته‌ها:\n{packages}",
    "adm_referral_pkg_item": "• *{name}* — {credits} اعتبار | {data} GB / {days}d / {ip} IP | {status}",
    "adm_referral_pkg_none": "(بسته‌ای نیست)",
    "adm_referral_add_pkg": "➕ افزودن بسته",
    "adm_referral_pkg_name_prompt": "نام بسته را وارد کنید:",
    "adm_referral_pkg_credits_prompt": "تعداد اعتبار دعوت لازم برای دریافت را وارد کنید:",
    "adm_referral_pkg_data_prompt": "محدودیت حجم را به گیگابایت وارد کنید (۰ برای نامحدود):",
    "adm_referral_pkg_days_prompt": "مدت زمان را به روز وارد کنید (۰ برای بی‌انقضا):",
    "adm_referral_pkg_ip_prompt": "محدودیت IP را وارد کنید (۰ برای نامحدود):",
    "adm_referral_pkg_nodes_prompt": "نودهای این بسته دعوتی را انتخاب کنید:",
    "adm_referral_pkg_created": "✅ بسته دعوتی ایجاد شد.",
    "adm_referral_pkg_deleted": "🗑️ بسته دعوتی حذف شد.",
    "btn_set_referral": "👥 سیستم دعوت",
    "adm_referral_pkg_detail": "🎁 *{name}*\n\n💾 حجم: {data_text}\n📅 مدت: {days_text}\n📱 محدودیت IP: {ip_text}\n⭐ اعتبار لازم: {credits}\nوضعیت: {status}",
    "adm_referral_bulk_nodes_select_pkgs_prompt": "بسته‌های دعوتی که نودهایشان باید تغییر کند را انتخاب کنید:",
    "adm_referral_pkg_nodes_bulk_done": "✅ نودها برای {count} بسته بروزرسانی شد.",
    "btn_adm_broadcast": "📢 ارسال همگانی",
    "adm_broadcast_prompt": "پیامی که می‌خواهید برای همه کاربران ارسال کنید را بفرستید (از Markdown پشتیبانی می‌شود):",
    "adm_broadcast_done": "✅ پیام به {sent}/{total} کاربر ارسال شد.",
    "btn_adm_notifications": "🔔 اعلان‌ها",
    "adm_notifications_title": "🔔 *اعلان‌های ادمین*\n\nرویدادهایی که می‌خواهید اعلان دریافت کنید را تنظیم کنید.",
    "adm_notif_sub_start_msg_prompt": "پیامی که هنگام شروع استفاده اشتراک برای کاربران ارسال می‌شود را وارد کنید (- برای استفاده از پیش‌فرض):\nفعلی: {current}",
    "adm_notif_sub_start_msg_default": "▶️ اشتراک شما شروع به استفاده شد!",
    "notif_label_discount": "🏷️ کد تخفیف",
    "notif_label_payment_link": "🔗 لینک پرداخت",
    "notif_label_purchase": "💰 خرید",
    "notif_label_trial": "🎁 آزمایشی",
    "notif_label_sub_start": "▶️ اولین استفاده اشتراک",
    "notif_btn_sub_start_msg": "✏️ پیام شروع اشتراک",
    "btn_wallet_adjust": "💳 کیف پول",
    "adm_wallet_title": "💳 *کیف پول*\nموجودی: *{balance}*",
    "adm_wallet_add_prompt": "مقدار اعتباری که می‌خواهید اضافه کنید را وارد کنید:",
    "adm_wallet_remove_prompt": "مقدار اعتباری که می‌خواهید کم کنید را وارد کنید (موجودی فعلی: {balance}):",
    "adm_wallet_adjusted": "✅ انجام شد. موجودی جدید: {balance}",
    "adm_wallet_invalid": "❌ مقدار نامعتبر.",
    "adm_wallet_insufficient": "❌ موجودی ناکافی.",
    "btn_wallet_add": "➕ افزودن اعتبار",
    "btn_wallet_remove": "➖ کم کردن اعتبار",
    "wallet_info": "💳 کیف پول: {balance}",
    "btn_wallet_use": "✅ استفاده از {amount} اعتبار کیف پول",
    "btn_wallet_enable": "💳 استفاده از {amount} از کیف پول",
    "wallet_order_created": "✅ با اعتبار کیف پول پرداخت شد!\n\n🔗 اشتراک شما: `{url}`",
    "wallet_order_fail": "❌ ایجاد اشتراک ناموفق بود.",
    "btn_consumer_wallet": "💳 کیف پول",
    "wallet_panel": "💳 *کیف پول*\nموجودی: *{balance}*\n\nاعتبار اضافه کنید تا در خریدها استفاده کنید.",
    "wallet_topup_prompt": "مقداری که می‌خواهید به کیف پول اضافه کنید را وارد کنید:",
    "wallet_topup_invalid": "❌ مقدار نامعتبر. یک عدد مثبت وارد کنید.",
    "wallet_topup_pay_title": "💳 افزودن *{amount}* به کیف پول\nروش پرداخت را انتخاب کنید:",
    "wallet_topup_confirmed": "✅ *{amount}* به کیف پول شما اضافه شد!\nموجودی جدید: *{balance}*",
    "wallet_topup_label": "شارژ کیف پول",
    "btn_wallet_add_balance": "➕ افزودن موجودی",
    "referral_commission_info": "\n\n*💸 کمیسیون:* {status} | {pct}%",
    "btn_referral_commission_toggle": "💸 تغییر وضعیت کمیسیون",
    "btn_referral_commission_set_pct": "⚙️ تنظیم درصد کمیسیون",
    "adm_referral_commission_prompt": "درصد کمیسیون را وارد کنید (مثلاً ۱۰ برای ۱۰٪):",
    "referral_commission_earned": "💸 شما *{amount}* اعتبار کیف پول از خرید یک رفرال کسب کردید!",
    "adm_users_list": "👥 *کاربران* (مجموع {total}، صفحه {page}/{pages})\n\n",
}

def t(key, **kwargs):
    lang = settings.LANGUAGE.lower()
    strings = _FA if lang=="fa" else _EN
    template = strings.get(key, _EN.get(key, key))
    return template.format(**kwargs) if kwargs else template
