from config import settings

_EN = {
    "welcome": "👋 Welcome to the VPN bot!\n\nUse the menu below to browse plans or check your subscription status.",
    "banned": "You are banned from using this bot.",
    "no_plans": "No plans available at the moment. Please check back later.",
    "plans_header": "📦 *Available Plans:*",
    "no_active_subs": "You have no active subscriptions. Use /plans to purchase one.",
    "sub_removed": "❌ Subscription expired or removed.",
    "support_contact": "💬 For support, contact: {support}",
    "support_no_contact": "💬 Please contact the bot administrator for support.",
    "support_purchase": "\n\nPlease contact {support} to purchase.",
    "support_purchase_no_contact": "\n\nPlease contact support to purchase.",
    "plan_detail": "📦 *{name}*\n\n💾 Data: {data_gb} GB\n📅 Duration: {days} days\n📱 IP Limit: {ip_limit}",
    "plan_price_line_card": "💳 Card: {price}",
    "plan_price_line_crypto": "🪙 Crypto: {price}",
    "plan_price_line_request": "🙋 Request: {price}",
    "plan_price_fallback": "💰 Price: {price}",
    "card_payment_info": "💳 Transfer *{price}* to:\n\nCard number: `{card_number}`\nName: *{card_holder}*\n\nAfter payment, send your receipt screenshot here.",
    "receipt_received": "Receipt received! ⏳ Waiting for admin confirmation.",
    "receipt_caption": "📩 New Payment Receipt\n\n👤 {first_name} (@{username})\n🆔 {telegram_id}\n📦 Plan: {plan_name}\n💰 Amount: {amount}",
    "sub_confirmed": "✅ Your subscription has been confirmed!\n\n🔗 Link: `{url}`\n\nImport this link into your VPN app.",
    "sub_rejected": "❌ Your payment was rejected. Please contact support if you believe this is an error.",
    "request_created": "🙋 Your subscription request has been submitted. An admin will review it shortly.",
    "request_caption": "🙋 Subscription Request\n\n👤 {first_name} (@{username})\n🆔 {telegram_id}\n📦 Plan: {plan_name}\n📝 Reason: {reason}",
    "request_no_reason": "(no reason provided)",
    "request_approved": "✅ Your subscription request has been approved!\n\n🔗 Link: `{url}`\n\nImport this link into your VPN app.",
    "request_declined": "❌ Your subscription request was declined.",
    "crypto_invoice_created": "🪙 Pay with Crypto\n\nAmount: {amount}\n\nClick the button below to complete payment.",
    "crypto_paid": "✅ Crypto payment confirmed!\n\n🔗 Link: `{url}`\n\nImport this link into your VPN app.",
    "service_unavailable": "⚠️ Service temporarily unavailable. Please try again later.",
    "sub_orphaned": "⚠️ Your subscription has been removed from the server. Please contact support.",
    "admin_confirmed": "✅ Confirmed by {admin}\nSub ID: {sub_id}",
    "admin_rejected": "❌ Rejected by {admin}",
    "wizard_step1": "⚙️ *First-Run Setup*\n\nStep 1/4 — GhostGate URL\n\nEnter the full panel URL including the secret path.\nExample: `https://vpn.example.com/mySecretPath`",
    "wizard_step1_fail": "❌ Could not connect: {error}\n\nTry again:",
    "wizard_step2": "Step 2/4 — Support Contact\n\nEnter a @username for users to contact for support. (e.g. @support)",
    "wizard_step3a": "Step 3/4 — Card-to-Card Payment\n\nEnter card number (e.g. 6037-9975-XXXX-XXXX):",
    "wizard_step3b": "Enter cardholder name:",
    "wizard_step3c": "Step 3/4 — Cryptomus (optional)\n\nEnter your Cryptomus Merchant ID:",
    "wizard_step3d": "Enter your Cryptomus API Key:",
    "wizard_step4": "Step 4/4 — Base Currency\n\nEnter base currency code (e.g. IRT, USD, USDT):\nThis is the unit in which plan prices will be set.",
    "wizard_done": "✅ Setup complete!\n\nYou can add more currencies with different exchange rates in Settings → Currencies.",
    "btn_skip": "⏭️ Skip",
    "btn_back": "⬅️ Back",
    "admin_menu_title": "👑 *Admin Panel*",
    "plans_title": "🗂️ *Plans*\n\nSelect a plan to manage:",
    "no_plans_admin": "No plans created yet.",
    "plan_created": "✅ Plan created.",
    "plan_deleted": "🗑️ Plan deleted.",
    "setting_saved": "✅ Setting saved.",
    "enter_value": "Enter new value:",
    "sub_created_admin": "✅ Subscription created.\nSub ID: {sub_id}\nLink: `{url}`",
    "sub_deleted": "🗑️ Subscription deleted.",
    "user_banned": "🚫 User banned.",
    "user_unbanned": "🔓 User unbanned.",
    "admin_added": "✅ Admin added.",
    "admin_removed": "🗑️ Admin removed.",
    "invalid_input": "❌ Invalid input. Please try again.",
    "order_not_found": "Order not found.",
    "ghostgate_error": "❌ Failed to communicate with GhostGate. Please try again.",
    "reason_prompt": "Do you want to provide a reason? Type it or press Skip:",
    "reject_reason_prompt": "Enter rejection reason (or press Skip to send without reason):",
    "reject_notif": "❌ Your payment was rejected.\n\nReason: {reason}",
    "curr_title": "💱 *Currencies*\nBase: {base}\n\nSelect a currency to manage:",
    "curr_no_currencies": "💱 *Currencies*\nBase: {base}\n\nNo additional currencies configured.",
    "curr_detail": "💱 *{code}* — {name}\nDecimals: {decimals}\nMethods: {methods}\nRate: 1 {base} = {rate} {code}",
    "curr_add_code": "Enter currency code (e.g. IRT, USDT, USD):",
    "curr_add_name": "Enter display name (e.g. Toman, Tether, Dollar):",
    "curr_add_decimals": "Enter decimal places (0 for IRT, 2 for USDT):",
    "curr_add_methods": "Select which payment methods use this currency:",
    "curr_add_rate_prompt": "1 {code} = ? {base}\n\n(e.g. enter 40000 if 1 USDT = 40,000 IRT):",
    "curr_added": "✅ Currency {code} added.",
    "curr_deleted": "🗑️ Currency deleted.",
    "curr_rate_updated": "✅ Rate updated.",
    "curr_set_base_prompt": "Select which currency to use as base (plan prices are entered in this unit):",
    "curr_base_set": "✅ Base currency set to {code}.",
    "plan_price_enter": "Enter price in {base} (e.g. 500000):",
    "trial_info": "🎁 *Free Trial*\n\n{data_gb} GB • {expire_h}h from first use\n\nClaim your one-time free trial!",
    "trial_not_available": "🎁 Free trial is not available at the moment.",
    "trial_already_claimed": "🎁 You have already claimed your free trial.",
    "trial_claimed": "🎁 Your free trial is ready!\n\n🔗 Link: `{url}`\n\nImport this link into your VPN app. Your trial starts on first connection.",
    "trial_settings": "🎁 *Trial Subscription*\n\nStatus: {status}\nData: {data_gb} GB\nExpiry: {expire_h}h after first use\nNodes: {node_count} configured",
    "trial_data_prompt": "Enter trial data limit in GB (e.g. 0.5):",
    "trial_expire_prompt": "Enter trial duration in hours after first use (e.g. 24):",
}

_FA = {
    "welcome": "👋 به ربات VPN خوش آمدید!\n\nاز منوی زیر می‌توانید پلان‌ها را مشاهده یا وضعیت اشتراک خود را بررسی کنید.",
    "banned": "شما از استفاده از این ربات محروم شده‌اید.",
    "no_plans": "در حال حاضر پلانی موجود نیست. لطفاً بعداً بررسی کنید.",
    "plans_header": "📦 *پلان‌های موجود:*",
    "no_active_subs": "شما اشتراک فعالی ندارید. از /plans برای خرید استفاده کنید.",
    "sub_removed": "❌ اشتراک منقضی یا حذف شده است.",
    "support_contact": "💬 برای پشتیبانی با {support} تماس بگیرید.",
    "support_no_contact": "💬 برای پشتیبانی با مدیر ربات تماس بگیرید.",
    "support_purchase": "\n\nبرای خرید با {support} تماس بگیرید.",
    "support_purchase_no_contact": "\n\nبرای خرید با پشتیبانی تماس بگیرید.",
    "plan_detail": "📦 *{name}*\n\n💾 حجم: {data_gb} گیگابایت\n📅 مدت: {days} روز\n📱 محدودیت IP: {ip_limit}",
    "plan_price_line_card": "💳 کارت: {price}",
    "plan_price_line_crypto": "🪙 رمزارز: {price}",
    "plan_price_line_request": "🙋 درخواست: {price}",
    "plan_price_fallback": "💰 قیمت: {price}",
    "card_payment_info": "💳 مبلغ *{price}* را به کارت زیر واریز کنید:\n\nشماره کارت: `{card_number}`\nنام: *{card_holder}*\n\nپس از پرداخت، تصویر رسید خود را ارسال کنید.",
    "receipt_received": "رسید دریافت شد! ⏳ در انتظار تأیید مدیر.",
    "receipt_caption": "📩 رسید جدید\n\n👤 {first_name} (@{username})\n🆔 {telegram_id}\n📦 پلان: {plan_name}\n💰 مبلغ: {amount}",
    "sub_confirmed": "✅ اشتراک شما تأیید شد!\n\n🔗 لینک: `{url}`\n\nاین لینک را در اپلیکیشن VPN خود وارد کنید.",
    "sub_rejected": "❌ پرداخت شما رد شد. اگر اشتباهی رخ داده، با پشتیبانی تماس بگیرید.",
    "request_created": "🙋 درخواست اشتراک شما ثبت شد. یک مدیر به زودی آن را بررسی می‌کند.",
    "request_caption": "🙋 درخواست اشتراک\n\n👤 {first_name} (@{username})\n🆔 {telegram_id}\n📦 پلان: {plan_name}\n📝 دلیل: {reason}",
    "request_no_reason": "(بدون دلیل)",
    "request_approved": "✅ درخواست اشتراک شما تأیید شد!\n\n🔗 لینک: `{url}`\n\nاین لینک را در اپلیکیشن VPN خود وارد کنید.",
    "request_declined": "❌ درخواست اشتراک شما رد شد.",
    "crypto_invoice_created": "🪙 پرداخت با رمزارز\n\nمبلغ: {amount}\n\nبرای پرداخت روی دکمه زیر کلیک کنید.",
    "crypto_paid": "✅ پرداخت رمزارزی تأیید شد!\n\n🔗 لینک: `{url}`\n\nاین لینک را در اپلیکیشن VPN خود وارد کنید.",
    "service_unavailable": "⚠️ سرویس موقتاً در دسترس نیست. لطفاً دوباره امتحان کنید.",
    "sub_orphaned": "⚠️ اشتراک شما از سرور حذف شده است. لطفاً با پشتیبانی تماس بگیرید.",
    "admin_confirmed": "✅ تأیید شد توسط {admin}\nشناسه اشتراک: {sub_id}",
    "admin_rejected": "❌ رد شد توسط {admin}",
    "wizard_step1": "⚙️ *راه‌اندازی اولیه*\n\nمرحله ۱/۴ — آدرس GhostGate\n\nآدرس کامل پنل شامل مسیر مخفی را وارد کنید.\nمثال: `https://vpn.example.com/mySecretPath`",
    "wizard_step1_fail": "❌ خطا در اتصال: {error}\n\nدوباره امتحان کنید:",
    "wizard_step2": "مرحله ۲/۴ — تماس پشتیبانی\n\nیک @username برای پشتیبانی کاربران وارد کنید. (مثال: @support)",
    "wizard_step3a": "مرحله ۳/۴ — پرداخت کارت به کارت\n\nشماره کارت را وارد کنید (مثال: ۶۰۳۷-۹۹۷۵-XXXX-XXXX):",
    "wizard_step3b": "نام صاحب کارت را وارد کنید:",
    "wizard_step3c": "مرحله ۳/۴ — Cryptomus (اختیاری)\n\nMerchant ID خود را وارد کنید:",
    "wizard_step3d": "API Key خود را وارد کنید:",
    "wizard_step4": "مرحله ۴/۴ — ارز پایه\n\nکد ارز پایه را وارد کنید (مثال: IRT، USD، USDT):\nقیمت پلان‌ها با این واحد وارد می‌شود.",
    "wizard_done": "✅ راه‌اندازی کامل شد!\n\nمی‌توانید ارزهای بیشتر با نرخ تبدیل را از تنظیمات → ارزها اضافه کنید.",
    "btn_skip": "⏭️ رد کردن",
    "btn_back": "⬅️ بازگشت",
    "admin_menu_title": "👑 *پنل مدیریت*",
    "plans_title": "🗂️ *پلان‌ها*\n\nیک پلان را برای مدیریت انتخاب کنید:",
    "no_plans_admin": "هنوز پلانی ایجاد نشده.",
    "plan_created": "✅ پلان ایجاد شد.",
    "plan_deleted": "🗑️ پلان حذف شد.",
    "setting_saved": "✅ تنظیم ذخیره شد.",
    "enter_value": "مقدار جدید را وارد کنید:",
    "sub_created_admin": "✅ اشتراک ایجاد شد.\nشناسه: {sub_id}\nلینک: `{url}`",
    "sub_deleted": "🗑️ اشتراک حذف شد.",
    "user_banned": "🚫 کاربر مسدود شد.",
    "user_unbanned": "🔓 کاربر مسدودیت‌زدایی شد.",
    "admin_added": "✅ مدیر اضافه شد.",
    "admin_removed": "🗑️ مدیر حذف شد.",
    "invalid_input": "❌ ورودی نامعتبر. لطفاً دوباره امتحان کنید.",
    "order_not_found": "سفارش یافت نشد.",
    "ghostgate_error": "❌ ارتباط با GhostGate ناموفق بود. دوباره امتحان کنید.",
    "reason_prompt": "آیا می‌خواهید دلیلی وارد کنید؟ تایپ کنید یا رد کردن را بزنید:",
    "reject_reason_prompt": "دلیل رد را وارد کنید (یا رد کردن را بزنید):",
    "reject_notif": "❌ پرداخت شما رد شد.\n\nدلیل: {reason}",
    "curr_title": "💱 *ارزها*\nپایه: {base}\n\nیک ارز را برای مدیریت انتخاب کنید:",
    "curr_no_currencies": "💱 *ارزها*\nپایه: {base}\n\nهنوز ارز اضافه‌ای پیکربندی نشده.",
    "curr_detail": "💱 *{code}* — {name}\nاعشار: {decimals}\nروش‌ها: {methods}\nنرخ: ۱ {base} = {rate} {code}",
    "curr_add_code": "کد ارز را وارد کنید (مثال: IRT، USDT، USD):",
    "curr_add_name": "نام نمایشی را وارد کنید (مثال: تومان، تتر، دلار):",
    "curr_add_decimals": "تعداد اعشار را وارد کنید (۰ برای تومان، ۲ برای تتر):",
    "curr_add_methods": "روش‌های پرداختی که از این ارز استفاده می‌کنند را انتخاب کنید:",
    "curr_add_rate_prompt": "۱ {code} = ? {base}\n\n(مثال: ۴۰۰۰۰ اگر ۱ USDT = ۴۰٬۰۰۰ تومان باشد):",
    "curr_added": "✅ ارز {code} اضافه شد.",
    "curr_deleted": "🗑️ ارز حذف شد.",
    "curr_rate_updated": "✅ نرخ به‌روزرسانی شد.",
    "curr_set_base_prompt": "ارزی که قیمت پلان‌ها با آن وارد می‌شود را انتخاب کنید:",
    "curr_base_set": "✅ ارز پایه به {code} تغییر کرد.",
    "plan_price_enter": "قیمت را به {base} وارد کنید (مثال: ۵۰۰۰۰۰):",
    "trial_info": "🎁 *آزمایشی رایگان*\n\n{data_gb} گیگ • {expire_h} ساعت از اولین اتصال\n\nاشتراک آزمایشی یک‌بار مصرف خود را دریافت کنید!",
    "trial_not_available": "🎁 در حال حاضر اشتراک آزمایشی موجود نیست.",
    "trial_already_claimed": "🎁 شما قبلاً اشتراک آزمایشی خود را دریافت کرده‌اید.",
    "trial_claimed": "🎁 اشتراک آزمایشی شما آماده است!\n\n🔗 لینک: `{url}`\n\nاین لینک را در اپلیکیشن VPN وارد کنید. تایمر از اولین اتصال شروع می‌شود.",
    "trial_settings": "🎁 *اشتراک آزمایشی*\n\nوضعیت: {status}\nحجم: {data_gb} گیگابایت\nانقضا: {expire_h} ساعت پس از اولین اتصال\nنودها: {node_count} پیکربندی‌شده",
    "trial_data_prompt": "حجم آزمایشی را به گیگابایت وارد کنید (مثال: ۰.۵):",
    "trial_expire_prompt": "مدت آزمایشی را به ساعت وارد کنید (مثال: ۲۴):",
}

def t(key, **kwargs):
    lang = settings.LANGUAGE.lower()
    strings = _FA if lang=="fa" else _EN
    template = strings.get(key, _EN.get(key, key))
    return template.format(**kwargs) if kwargs else template
